### ISSUE TITLE
NumberEntity method deprecating and will be unsupported from Home Assistant 2022.10 - alerting custom integration author

### ISSUE THREAD

**Issue by ziptbm** [simbaja/ha_gehome#105]
I'm seeing the following in my logs for each reboot, so sharing here per the error recommendation.

`Logger: homeassistant.components.number
Source: components/number/__init__.py:231
Integration: Number (documentation, issues)
First occurred: 20:37:29 (3 occurrences)
Last logged: 20:37:30

custom_components.ge_home.entities.common.ge_erd_number::GeErdNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.ge_home.entities.ccm.ge_ccm_brew_temperature::GeCcmBrewTemperatureNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.ge_home.entities.ccm.ge_ccm_brew_cups::GeCcmBrewCupsNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.`

**Comment by simbaja** [comment]
Yep, fixed in the dev branch (and in the pre-release if you want to try through HACS)

**Comment by ziptbm** [comment]
Thanks.  Will this fix be merged into the main branch or do we just need to move to dev/pre-release? @simbaja

**Comment by simbaja** [comment]
It will once a few other features are finished.
