### ISSUE TITLE
Devices not being displayed

### ISSUE THREAD

**Issue by pablinho1023** [simbaja/ha_gehome#106]
Hello.
I just added the repo to my HA and restarted but nothing happened. I have checked the custom_components folder and the ge_home is there. I have a Washer and a Dryer. Is there anything else that needs to be added or something that I am missing?

Thank you.

**Comment by simbaja** [comment]
Did you add it as an integration?  You need to add the custom component, then configure it using your SmartHQ credentials.

**Comment by simbaja** [comment]
Once added via HACS, it needs to be configured like any other built-in integration as well.

**Comment by pablinho1023** [comment]
I see. I found how to add it as an integration in the devices tab. However it got an error. Config flow could not be loaded: undefined

**Comment by pablinho1023** [comment]
It worked after I restarted HA. However, I need to integrate it again every time it is restarted to input my credentials.
Thanks for the help.
