### ISSUE TITLE
GE Cafe fridge/freezer temps not updating

### ISSUE THREAD

**Issue by cmj3d** [simbaja/ha_gehome#111]
Since Aug 30, the current temperatures for my GE Cafe fridge and freezer are no longer updating. Prior to this, they would change regularly throughout the day, usually 1-2 degrees around the setpoint.  All other sensors seem to be working and updating just fine, such as the door status, ice maker bucket status, and the hot water dispenser temperature.  

I've tried both the master and 0.6.5-dev2 versions, with the same result.  Currently running GE Home 0.6.5-dev2 and HA 2022.9.6.

No errors jump out in the HA logs.

Highlighted sensors remain at 0 and 38 degrees respectively:
![GE cafe](https://user-images.githubusercontent.com/59585349/192162628-f7048ef1-8d45-40c7-bcf1-86cfb9986409.jpg)

Temp history for the last 10 days - no changes:
![GE Cafe temp history](https://user-images.githubusercontent.com/59585349/192162688-0ed18ee4-2503-4a59-ab03-63fe27dea2d9.jpg)

prior to Aug 30, temps were updating frequently:
![fridge temps_1 week-update-v2](https://user-images.githubusercontent.com/59585349/192162917-65cb02ea-db3a-43eb-90f3-33c1aa7e9cfc.png)

**Comment by simbaja** [comment]
I see the same behavior on mine.  It's just pulling this information from the API, so guessing something changed there and they decided to not report it (or broke it).

**Comment by TiddlyWiddly** [comment]
I noticed this today too when my SmartHQ app told me the freezer temperature had reached 20F and I checked HA and saw that it hadn't updated for a long time. I checked the SmartHQ app too and it says that the freezer was 0, even though the notification told me 20F and even though I visibly saw that it had started to defrost. I wonder if they changed entity names or something in the API.

**Comment by simbaja** [comment]
Very interesting, so it's still somehow getting this information, but perhaps it's not being exposed.  Seems like a bug to me.

**Comment by YBonline** [comment]
I just got a new GE Profile fridge, and it initially updated temperatures, then it got a firmware update on day 2 and stopped updating

**Comment by simbaja** [comment]
Looks like this is broken by GE, closing :(

**Comment by TiddlyWiddly** [comment]
@simbaja -- is it possible that they changed the ERD code for this? If I leave gehome-appliance-data running long enough I can see these come through:

Setting ErdCode.FRIDGE_UNKNOWN_1101 to b'\x00\x006\x9f\x00\x01<s\x0f_\x11\xab\x00\x00\x04F'
Setting ErdCode.FRIDGE_UNKNOWN_1101 to b'\x00\x006\x9f\x00\x01=\x14\x0f`\x11\xab\x00\x00\x04F'

**Comment by simbaja** [comment]
If they did, they are in a completely different format - the original values were simple integers, that's a lot of data that would need to be deciphered..
