### ISSUE TITLE
GE Range does not appear in HomeAssistant

### ISSUE THREAD

**Issue by Strider0** [simbaja/ha_gehome#116]
My vent hood and refrigerator appear in HomeAssistant (version 2022.8.7), but the range (CGY366P2TS1) does not.  I tried the main branch and the dev branch, restarting the machine, HomeAssistant, etc.
The logs show the following error:
Logger: homeassistant
Source: custom_components/ge_home/devices/oven.py:96
Integration: GE Home ([documentation](https://github.com/simbaja/ha_gehome))
First occurred: 9:48:28 AM (1 occurrences)
Last logged: 9:48:28 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 301, in on_device_initial_update
    self.maybe_add_appliance_api(appliance)
  File "/config/custom_components/ge_home/update_coordinator.py", line 133, in maybe_add_appliance_api
    api.build_entities_list()
  File "/config/custom_components/ge_home/devices/base.py", line 135, in build_entities_list
    e for e in self.get_all_entities()
  File "/config/custom_components/ge_home/devices/oven.py", line 96, in get_all_entities
    cooktop_status: CooktopStatus = self.appliance.get_erd_value(ErdCode.COOKTOP_STATUS)
  File "/usr/local/lib/python3.10/site-packages/gehomesdk/ge_appliance.py", line 136, in get_erd_value
    return self._property_cache[erd_code]
KeyError: <ErdCode.COOKTOP_STATUS: '0x5520'>

Any advice?

**Comment by simbaja** [comment]
I think I've at least resolved the error, but it may be that the device either a) doesn't have the cooktop status or b) it's showing up differently from other ranges.  For now, the latest dev version shouldn't error out, but it won't have the cooktop status either.  If the app is showing the status, can you go over to the sdk repository (simbaja/gehome) and follow the instructions to produce a log file so I can see what it is sending?

**Comment by Strider0** [comment]
Yes.  The error is gone.  The  oven now shows in HA. (seems to think it's a water heater).  The cooktop doesn't.  Attached is the log output.  Thanks for your work on this.  It is great to have my appliances in HA.
[gehome_logs.txt](https://github.com/simbaja/ha_gehome/files/9835815/gehome_logs.txt)
