### ISSUE TITLE
Cannot delete this integration

### ISSUE THREAD

**Issue by jazzmonger** [simbaja/ha_gehome#118]
No matter what I try, I cannot delete this integration:

The following integrations and platforms could not be set up:
    ge_home ([Show logs](http://192.168.1.250:8123/config/logs?filter=ge_home))

I've completely removed the directory from custom_components, removed the integration from HA and restarted a dozen times.  NO entries appear in the log file. Nothing in any config files I can find. Anyone know how I can get past this?  I'm stuck and cannot UG until I get rid of this thing.

Jeff

**Comment by simbaja** [comment]
That's very odd, what order did you do those steps?  I'd advise putting the custom component back (so that there's something in custom_components), then remove from HA, then delete the custom_component files.  If that doesn't work, you can try editing the config entries directly to remove the entry.  Just be careful with that and back everything up, if you get it wrong it could hose your entire installation.

**Comment by jazzmonger** [comment]
I finally ended up doing that and it worked. 

> On Oct 16, 2022, at 7:42 AM, simbaja ***@***.***> wrote:
> 
> ﻿
> That's very odd, what order did you do those steps? I'd advise putting the custom component back (so that there's something in custom_components), then remove from HA, then delete the custom_component files. If that doesn't work, you can try editing the config entries directly to remove the entry. Just be careful with that and back everything up, if you get it wrong it could hose your entire installation.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

-- 


This message may contain confidential and/or privileged information. If 
you are not the addressee or are not authorized to receive this for the 
addressee, you must not use, copy, disclose, or take any action based on 
this message or any information herein. If you have received this message 
in error, please advise the sender immediately by reply email and delete 
this message.
