### ISSUE TITLE
Integration consistently fails to set up on HA restart

### ISSUE THREAD

**Issue by GitHubGoody** [simbaja/ha_gehome#119]
Every time I restart HA, this integration fails to set up

![image](https://user-images.githubusercontent.com/46235745/196039731-424a0fb9-26a0-42c6-a1dd-a44d4a35d4e8.png)

The logs do not provide anything useful for troubleshooting.

Reloading the integration usually fixes it within seconds on the first try.

**Comment by simbaja** [comment]
Use the dev version for now, resolves this issue.

**Comment by GitHubGoody** [comment]
@simbaja I see there's an updated release in HACS. Does that containt the same bug fixes as the dev version?
