### ISSUE TITLE
GE Double Oven Sensor Unavailable.

### ISSUE THREAD

**Issue by mrbeamstx** [simbaja/ha_gehome#133]
GE Double Oven  Lower Oven Temperature Display  entity is unavailable.
![image](https://user-images.githubusercontent.com/121527263/209842768-221af774-e80c-4a05-be19-e02608a26bc6.png)

**Comment by mrbeamstx** [comment]
Additional Question.  I installed through HACS.  I cannot find or create the Oven Control Card.  Any guidance?

**Comment by simbaja** [comment]
Hmm, that's odd, does it show up properly in SmartHQ?  As to your second question, there's no separate control card, it pretends to be a water heater device and leverages the standard HASS functionality for those devices.  Once the entity shows, you'll have this card available.
