### ISSUE TITLE
Washer / Dryer entities "unavailable"

### ISSUE THREAD

**Issue by outrageouskiwi** [simbaja/ha_gehome#136]
Very excited about this integration, I appreciate all of the work. I am new to Home Assistant, so please bear with me!

I have a GE smartHQ washer and dryer. My only goal is to get notified when a machine cycle is complete—and here's the rub—without letting my washer/dryer get online. (I have a hardware firewall and keep all of my IoT devices in a 'no web access' group.)

When I first installed the component, it listed 2 devices (my washer/dryer) and 34 entities. At first, it showed 17 as "unavailable" and 17 as available. At some point, the other 17 entities became unavailable as well. 

Things I have tried: Power cycling the washer / dryer; making sure I test with both machines on; rebooting Home Assistant (rPi4, 8GB); setting up an automation (although it's my first, I set 'condition' to 'Laundry End of Cycle is on' and 'action' to 'Send a notification with notify,' and when I hit 'run' I get a notification. 

When I last started up HA, the logs said: 

> Waiting on integrations to complete setup: ge_home
> 2:33:07 PM – (WARNING) bootstrap.py
> Using slower stringprep, consider compiling the faster cython/libidn one.
> 2:33:06 PM – (WARNING) GE Home (custom integration)
> 
> 2023-01-17 14:31:35.265 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration ge_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2023-01-17 14:33:06.814 WARNING (MainThread) [slixmpp.stringprep] Using slower stringprep, consider compiling the faster cython/libidn one.
> 2023-01-17 14:33:07.437 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: ge_home

My questions: 

1. Do the washer and dryer require internet access for this integration to function?
2. Should I expect all 34 entities to be available?
3. (Dumb question, but: Will my entities be unavailable when the washer and dryer are not powered on?)
4. What can I do to make the entities available / achieve my goal of getting notified when laundry is ready or dry?
5. What additional logs can I provide to help troubleshoot?

Thank you in advance for any help!

**Comment by barcherf5** [comment]
1. I believe the answer is "yes", but @simbaja can confirm. I think they have to be registered in the app, thus being online.
2. Not sure.
3. If they are completely unplugged, yes, but it's likely that the units have a 'low power when not in use' feature, like a 'ready' state. Again, not sure.
4. Not sure.
5. Without the units being 'online', I don't know that any amount of logging will help.

**Comment by warrenrees** [comment]
Good morning,

Please find the answers to your questions

1. Both the washer and dryer require constant internet connection in order for this integration to work.  The appliances publish their state to the GE servers and this integration reaches out to GE's servers and pulls the data from there with regard to status.  There is no local connection to the appliances themselves.
2. Yes all entities would be available when the appliances are connected to the internet and home assistant can connect to the API endpoint
3. If the appliances are plugged in and they have internet connectivity to the GE api, the entities will be available. 
4. Ensure that the appliances are able to connect to the GE api, without this, the integration will not work.
5. None, appliances need internet/API connectivity.

**Comment by barcherf5** [comment]
This does bring up an interesting question, though. Might it be possible to intercept the traffic back to GE and interpret/control locally?

**Comment by outrageouskiwi** [comment]
Thank you! I created an isolated firewall group and gave web access to my washer and dryer. All of the entities appear now.

Side note, do I have my automation set correctly to notify me when laundry is complete? I attached a photo—the trigger is “laundry end of cycle turned off” with no duration, and the action is notify.notify.

**Comment by barcherf5** [comment]
Pic didn't come through, I think.

I think you'd want "laundry end of cycle turned on", though? Maybe look at the history of that entity and see which is the more prevalent state?

**Comment by warrenrees** [comment]
![image](https://user-images.githubusercontent.com/33187409/213291123-dad8d63c-da9e-4cc2-a9c6-7859fcd360eb.png)

This is what I use to notify myself of when my washer/dryer finishes.  Works great.  I have a TTS and non-TTS one so that I don't want the kids up after their bedtime.
