### ISSUE TITLE
Water Softener

### ISSUE THREAD

**Issue by evilhyde** [simbaja/ha_gehome#138]
Hello, 

I'm new to home assistant so bear with me. I've added the integration and so far everything works well. I do however have an issue if I want to add my water consumption to my energy dashboard, I cannot select the entity. I believe this is due how is measuring the gallons, the energy dashboard is looking for 'gal' while the water consumption is set a 'g' on the plugin.

On the Homeassistant development page it show that Water consumption should be gal instead of g.

https://developers.home-assistant.io/docs/core/entity/sensor/

<html>
<body>

SensorDeviceClass.WATER | L, gal, m³, ft³, CCF | Water consumption
-- | -- | --

</body>
</html>
This is what the sensor currently has:

Daily Water Usage
33 state_class: total_increasing
unit_of_measurement: g
icon: mdi:water
friendly_name: Daily Water Usage

How can I change it from g to gal?

**Comment by simbaja** [comment]
I've made that update in the dev branch, so it will be available in the next version that's released.  There might need to be some more changes in this area as they've been making a lot of updates recently for these statistics.

**Comment by Morlince** [comment]
@simbaja I know you have been busy lately, but I'm not seeing this update in the dev branch.  Did this get resolved?  I'm on 0.6.6 dev1 and still see 'g' as the unit of measurement.  

I've tried modifying  the code to override the unit of measurement but it just breaks it.  I'm going to continue to work on it but thought I'd ask too.

**Comment by Morlince** [comment]
Thanks @simbaja looks good now.  I appreciating you getting that done.

**Comment by evilhyde** [comment]
> Thanks @simbaja looks good now. I appreciating you getting that done.

@Morlince Have you been able to add this to the Energy Dashboard?

**Comment by Morlince** [comment]
> > Thanks @simbaja looks good now. I appreciating you getting that done.
> 
> @Morlince Have you been able to add this to the Energy Dashboard?

Well darn, no I cannot.  I wonder if the deviceclass is still wrong and the label has just been changed...

Sorry to give you false hope.

**Comment by simbaja** [comment]
Should be fixed in newest pre-release based on the merge, but please let me know if it's not.
