### ISSUE TITLE
Enhancement Request: Warming Drawer Entities

### ISSUE THREAD

**Issue by claudermilk** [simbaja/ha_gehome#142]
I have the GE Cafe Oven model CGS986SEL2SS which has the warming drawer option. This isn't picked up by the current integration and it would be nice to see the on/off state and current setting (from the control panel: 1-Low, 2-Medium, 3-High).
I would be happy to provide any data I can but don't know what the appliance wants beyond IP address to pull any JSON if it will allow it, and I'm not seeing where any debug logs for the integration may be generated.

**Comment by simbaja** [comment]
Hey there, thanks for offering to help collect a bit of data.  If you go to the (https://github.com/simbaja/gehome)[simbaja/gehome] repository, the readme should give you the guidance to generate the debug information.

**Comment by claudermilk** [comment]
I must be dense. All I see in the readme is instructions for how to install the integration.

**Comment by simbaja** [comment]
Under "Usage" there's an application gehome-appliance-data that can generate the debug information.

**Comment by claudermilk** [comment]
Oh, I see. It's at https://github.com/simbaja/gehome. That link didn't work--I blame GitHub. It looks like something to install on the server via command line. Right now my HA server is gone :( I have a Yellow sitting waiting for a CM4 to hit stock somewhere, anywhere so I can get back up and running. I'll run this once I get the server back on its feet.

**Comment by claudermilk** [comment]
I have my HA Yellow all set up and things are running again. I tried to run the gehome-appliance-data application and it keeps throwing an authentication error at me. I've re-checked the credentials several times, and even copy-pasted the updated password I set from the brillion login that works (I had a ` in the old one which didn't get along with the command line). I tried with and without the -r US flag with no change. Here's the error message excluding the login webpage source it throws back as well:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gehomesdk/clients/async_login_flows.py", line 76, in async_get_authorization_code
    code = await async_handle_ok_response(session, await resp.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gehomesdk/clients/async_login_flows.py", line 111, in async_handle_ok_response
    raise GeAuthFailedError(f"Authentication failed, reason: {reason}")
gehomesdk.exception.ge_auth_failed_error.GeAuthFailedError: Authentication failed, reason: Invalid credentials
2023-06-24 06:56:52,731 ERROR    Task exception was never retrieved
future: <Task finished name='Task-1' coro=<GeBaseClient.async_get_credentials_and_run() done, defined at /usr/lib/python3.11/site-packages/gehomesdk/clients/base_client.py:117> exception=GeAuthFailedError('Could not obtain authorization code')>
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gehomesdk/clients/async_login_flows.py", line 76, in async_get_authorization_code
    code = await async_handle_ok_response(session, await resp.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gehomesdk/clients/async_login_flows.py", line 111, in async_handle_ok_response
    raise GeAuthFailedError(f"Authentication failed, reason: {reason}")
gehomesdk.exception.ge_auth_failed_error.GeAuthFailedError: Authentication failed, reason: Invalid credentials

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gehomesdk/clients/base_client.py", line 119, in async_get_credentials_and_run
    await self.async_get_credentials(session)
  File "/usr/lib/python3.11/site-packages/gehomesdk/clients/base_client.py", line 191, in async_get_credentials
    await self.async_do_full_login_flow()
  File "/usr/lib/python3.11/site-packages/gehomesdk/clients/base_client.py", line 195, in async_do_full_login_flow
    self.credentials = await self._async_do_full_login_flow()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gehomesdk/clients/websocket_client.py", line 63, in _async_do_full_login_flow
    await self._async_get_oauth2_token()
  File "/usr/lib/python3.11/site-packages/gehomesdk/clients/base_client.py", line 218, in _async_get_oauth2_token
    oauth_token = await async_get_oauth2_token(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gehomesdk/clients/async_login_flows.py", line 147, in async_get_oauth2_token
    code = await async_get_authorization_code(session, account_username, account_password, account_region)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gehomesdk/clients/async_login_flows.py", line 83, in async_get_authorization_code
    raise GeAuthFailedError(f'Could not obtain authorization code') from exc
gehomesdk.exception.ge_auth_failed_error.GeAuthFailedError: Could not obtain authorization code

**Comment by simbaja** [comment]
Interesting, so, this may be the error others are experiencing since upgrading.  Can you change your password to something simpler (no specials) and see if there's still a problem?

**Comment by claudermilk** [comment]
Aha! That was the issue. I now have some logged output to look at. The warming drawer has three settings: 1. Low 2. Medium 3. High. I grabbed the initial output and after cycling to each setting on the drawer. Hopefully this gives you what you need.
[gehome-appliance-data output.txt](https://github.com/simbaja/ha_gehome/files/11857782/gehome-appliance-data.output.txt)

**Comment by claudermilk** [comment]
Poking through the output I see this:
When set to low I see: Setting ErdCode.WARMING_DRAWER_STATE to b'\x01'
When set to medium (sorry, I labeled that low by accident): Setting ErdCode.WARMING_DRAWER_STATE to b'\x02'
When set to high I see: Setting ErdCode.WARMING_DRAWER_STATE to b'\x03'
THen off looks to be Setting ErdCode.WARMING_DRAWER_STATE to b'\x00'

**Comment by simbaja** [comment]
I haven't made a formal release, but if you pull down the dev branch, I think the drawers should be in (unless I made a typo somewhere).  I am waiting on a few more things before I start the next release cycle, but feel free to pull down manually and give it a shot.

**Comment by claudermilk** [comment]
I copied the updated files over into my install and restarted HA. The integration threw this error:
Logger: homeassistant.setup
Source: setup.py:215
First occurred: 8:15:28 AM (1 occurrences)
Last logged: 8:15:28 AM

Setup failed for custom integration ge_home: Unable to import component: cannot import name 'ErdOvenWarmingStateAvailability' from 'gehomesdk' (/usr/local/lib/python3.11/site-packages/gehomesdk/__init__.py)

The integration then won't load. Redownloaded from HACS and all is ok. It doesn't like that warming drawer definition.

**Comment by simbaja** [comment]
That particular error should be resolved.  I have to travel for work for the next few days, but let me know if it works now.  If not, I'll debug when I'm back home.

**Comment by claudermilk** [comment]
That works now! Thank you!
Integration reloaded ok, and I can see the warming drawer state updating.

**Comment by simbaja** [comment]
Excellent, this will get into the next release.  Thanks for the help!
