### ISSUE TITLE
Enhancement: GE Monarch ZDP486NDT1SS Oven Fields

### ISSUE THREAD

**Issue by tcgoetz** [simbaja/ha_gehome#144]
I have a GE Monarch ZDP486NDT1SS: https://www.geappliances.com/appliance/Monogram-48-Dual-Fuel-Professional-Range-with-6-Burners-and-Griddle-Natural-Gas-ZDP486NDTSS

Integrations mostly work. Some issues:

- Ovens are actually side by side, not upper/lower.
- Light control is only available for the lower oven.
- Lower oven temp is always shown at 0 degrees.
- Not all of the oven modes are shown correctly. It has the following modes: bake, broil, warm, proof, clean, convection broil, convection roast, and convection bake.

Log attached.

Thanks for your work! Let me know if I can help with this.
[ge_appliances.log](https://github.com/simbaja/ha_gehome/files/10803845/ge_appliances.log)

**Comment by simbaja** [comment]
Unfortunately, I can't do anything about the side by side vs. upper/lower - that's the way data is presented.  I'm sure that the official app maintains a mapping of some sort that indicates which model is which, but I don't really have the ability to do that.

In regard to the oven modes, not all are available, unfortunately.  I don't know why they limited it, but they didn't allow us to set a bunch of them (perhaps some sort of safety thing??).  

I think that I've got the others in the latest version that I'm working through right now, which I'll release shortly (hopefully).
