### ISSUE TITLE
Enhancement request: GE GUD27ESSM1WW Washer/Dryer fields

### ISSUE THREAD

**Issue by tcgoetz** [simbaja/ha_gehome#145]
I have a GUD27ESSM1WW washer/dryer that is coming up as only a washer.

Log attached.
[ge_appliances.log](https://github.com/simbaja/ha_gehome/files/10803879/ge_appliances.log)

Thanks for your work! Let me know if I can help with this.

**Comment by simbaja** [comment]
It's a bit odd, it looks like it's showing as a washer only.  What shows up in the official app?

**Comment by stellarore** [comment]
My GE stacked washer/dryer has separate RJ45 ports for the washer and dryer. They are mentioned in both washer and dryer sections in the manual. 

The GUD27ESSM1WW only has one port, and the manual only mentions the GE smart connect in the washer section. (Pg12) I don’t believe this model has any built in smart dryer functionality. 

https://www.manua.ls/ge/gud27essmww/manual

**Comment by simbaja** [comment]
Unfortunately, it doesn't look like we can do anything based on the above comment.  Feel free to request it reopened if you find new information.
