### ISSUE TITLE
Missing Entity with Double Oven 

### ISSUE THREAD

**Issue by jdc0730** [simbaja/ha_gehome#149]
I believe there is a minor bug in the following file:

/simbaja/ha_gehome/tree/master/custom_components/ge_home/devices/oven.py  

Line 67, I believe, should say LOWER instead of UPPER:

                GeErdSensor(self, ErdCode.LOWER_OVEN_DISPLAY_TEMPERATURE),

**Comment by simbaja** [comment]
Indeed it was a typo, fixed.  Thank you!
