### ISSUE TITLE
use of deprecated temperature helper will break component in HA 2023.4

### ISSUE THREAD

**Issue by Lx** [simbaja/ha_gehome#150]
> WARNING (`MainThread`) [`homeassistant.helpers.frame`] Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use `unit_conversion.TemperatureConverter` instead. Please report issue to the custom integration author for `ge_home` using this method at ...

https://github.com/simbaja/ha_gehome/blob/c8d77120c9702690ce01e334220df986580d20c0/custom_components/ge_home/entities/fridge/ge_abstract_fridge.py#L120
https://github.com/simbaja/ha_gehome/blob/c8d77120c9702690ce01e334220df986580d20c0/custom_components/ge_home/entities/fridge/ge_abstract_fridge.py#L129

**Comment by simbaja** [comment]
Please use the dev version ([v0.6.6-dev1](https://github.com/simbaja/ha_gehome/releases/tag/v0.6.6-dev1) it should resolve the issue.  I haven't deployed that to production yet due to an auth issue reported that I'm still tracking down.
