### ISSUE TITLE
[Request] Add support for Chef Connect Devices (Range Hoods, Microwaves, etc)

### ISSUE THREAD

**Issue by sdschramm** [simbaja/ha_gehome#157]
I have a GE Range Hood model: UVW8301SL1SS with "[Chef Connect](https://products.geappliances.com/appliance/gea-support-search-content?contentId=34456)" which uses Bluetooth to connect to a range/stove. The idea is that when you start cooking, it can automatically turn on the lights and/or fan. My stove doesn't have this feature, but I do have other sensors I could tie in, for example if the air quality becomes poor, turn on the vent fan. 

I'm running Home Assistant on a Lenovo M600 mini PC which has built in Bluetooth, but I haven't found any way to connect to the range hood. There is a pairing button you hold in for 3 seconds to enter pairing mode, but I'm not sure if it broadcasts anything, uses Bluetooth LE, etc. I know this may be a stretch and may not even be possible since it doesn't use WiFi but happy to help troubleshoot this if there is a potential it could work with this integration. Thanks!

**Comment by simbaja** [comment]
Don't know what can be done, but we can consolidate over on #147.  If it's available from the oven as a sensor, we can bring it in, but if not, it won't be possible from my understanding.
