### ISSUE TITLE
G.E Opal 2.0 Ice Maker [Filter Status: Problem]

### ISSUE THREAD

**Issue by rhodan412** [simbaja/ha_gehome#162]
In HA I notice that even after I change the filter and clean/descale my ice maker it reports Oim Filter Status: Problem. Is there a reset button in the integration to inform when I've changed the filter and cleaned/descaled it? I even took the ice maker apart and cleaned the tubes.

**Comment by simbaja** [comment]
Does the official app show that something needs to be done?

**Comment by simbaja** [comment]
Closing here, if there's something in the debug logs from the [sdk](https://github.com/simbaja/gehome), please let me know.
