### ISSUE TITLE
GE Monochrome - Missing Temperate

### ISSUE THREAD

**Issue by cdn4lf** [simbaja/ha_gehome#165]
Fridge and Freezer on GE Monochrome are missing current temperate. Everything else appears to be working properly.  Value is displayed as `null`

```
min_temp: -6
max_temp: 4
operation_list:
  - Normal
  - Sabbath Mode
  - Turbo Freeze
current_temperature: null
temperature: -3
target_temp_high: null
target_temp_low: null
operation_mode: Normal
door_status: Closed
ice_bucket: Not Full
ice_maker: 'Off'
icon: mdi:fridge-top
friendly_name: LR034139 Freezer
supported_features: 3
```

**Comment by simbaja** [comment]
Unfortunately, they seem to have removed temps from fridges at some point, annoying I know.  I don't think I can do anything, but please let me know if you see something promising in debug logs.
