### ISSUE TITLE
Feature Request: dishwasher filter notifications

### ISSUE THREAD

**Issue by tracymckibben** [simbaja/ha_gehome#167]
I have a GE Profile dishwasher, model #PDT785SYNFS. Your integration works great for 99% of what I'm looking for.

I'd love to remove the SmartHQ app from my phone, but there's one thing it provides for me that the integration does not - notification to clean the dishwasher filter.

What would it take to get that capability in the integration?
What logs can I provide for you to help make this happen?

**Comment by simbaja** [comment]
Hmm, the latest version of the integration should have that, it's under the "reminders".  Can you confirm you're using the latest version?

**Comment by simbaja** [comment]
I think it's in the latest version, closing for now, but ping if you are still having issues.
