### ISSUE TITLE
Message in log re using slower stringprep

### ISSUE THREAD

**Issue by kellyatkinson** [simbaja/ha_gehome#170]
My integration is working fine BUT I see a recurring message in my logs on every HA reboot:

`Using slower stringprep, consider compiling the faster cython/libidn one.`

Sounds like this is something that could be optimised in the integration's code?

The full log entry is included below.
```
This error originated from a custom integration.

Logger: slixmpp.stringprep
Source: custom_components/ge_home/update_coordinator.py:8
Integration: GE Home (documentation)
First occurred: 9:14:36 AM (1 occurrences)
Last logged: 9:14:36 AM

Using slower stringprep, consider compiling the faster cython/libidn one.
```

**Comment by simbaja** [comment]
Unfortunately that's in a dependent library and not under our control.
