### ISSUE TITLE
No longer seeing Air Conditioner

### ISSUE THREAD

**Issue by tbfistere** [simbaja/ha_gehome#171]
After HA 2023.6 core update, my GE Air Conditioner no longer appears on integration.

**Comment by yellowcooln** [comment]
I am having the same issue after updating to the following version:

Home Assistant 2023.6.1 
Supervisor 2023.06.1 
Operating System 10.2 
Frontend 20230608.0 - latest 

![image](https://github.com/simbaja/ha_gehome/assets/12516003/a3007aee-57c8-4cca-953a-d7632609dd12)
![image](https://github.com/simbaja/ha_gehome/assets/12516003/737ea5fd-3445-491c-a2b8-48aa7bdcfe14)

**Comment by lordtaytertot** [comment]
I don't have access to the logs at the moment, but this is due to an authentication failure, even though I've verified the supplied credentials are correct.  I'm seeing it with a non-AC device as well.

**Comment by FoxRx** [comment]
Same issue here.  After the upgrade to 2023.6 and 2023.6.1 the integration is no longer working.  I will post my log information.

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/ge_home/update_coordinator.py:174
Integration: GE Home (documentation)
First occurred: 8:32:44 AM (1 occurrences)
Last logged: 8:32:44 AM

Error setting up entry *******@yahoo.com for ge_home
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 172, in async_setup
    await self.initialization_future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 171, in async_setup
    with async_timeout.timeout(ASYNC_TIMEOUT):
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 116, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ge_home/__init__.py", line 26, in async_setup_entry
    if not await coordinator.async_setup():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ge_home/update_coordinator.py", line 174, in async_setup
    raise HaCannotConnect("Initialization timed out")
custom_components.ge_home.exceptions.HaCannotConnect: Initialization timed out

**Comment by piotroosh** [comment]
Same. 2023.6 breaks this integration. Log similar to the one above.

**Comment by ulli-us** [comment]
Same. Log similar to the one above.

**Comment by ulli-us** [comment]
Tried complete fresh re-install (manual) - still failing.

**Comment by techtim89** [comment]
Started getting a similar error accessing my GE Washer.  I updated to HA 2023.6.2 that just released.  Anyone have any thoughts?  The SmartHQ app on my iOS device displays the washer and it's status just fine.


This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/ge_home/update_coordinator.py:174
Integration: GE Home (documentation)
First occurred: 12:17:09 PM (2 occurrences)
Last logged: 5:02:15 PM

Error setting up entry ********@gmail.com for ge_home
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 172, in async_setup
    await self.initialization_future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ge_home/__init__.py", line 45, in async_setup_entry
    if not await coordinator.async_setup():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ge_home/update_coordinator.py", line 174, in async_setup
    raise HaCannotConnect("Initialization timed out")
custom_components.ge_home.exceptions.HaCannotConnect: Initialization timed out

**Comment by gsmalleus** [comment]
I am also experiencing this issue with my GE washer/dryer.  Initially broke with 2023.6.  I have updated to 2023.6.2  and I am seeing the same errors in my logs that techtim89 posted.

**Comment by simbaja** [comment]
Very odd, my HA is still working even after the upgrade to 2023.6.2.  The errors above seem to indicate some sort of timeout while trying to initialize the component.  Not sure why it would be failing, perhaps making the timeout longer would help?  if you look at custom_components/ge_home/const.py, if you change `ASYNC_TIMEOUT` to perhaps 60, does that make the issue go away?

**Comment by tbfistere** [comment]
I made the requested change.  The integration still is not detecting my air conditioner.

**Comment by simbaja** [comment]
Might need a full log then, it might be another error before this one that is causing initialization to fail.

**Comment by FoxRx** [comment]
I also changed the ASYNC_TIMEOUT to 60 and still receiving an error.  I will paste the log below:

![image](https://github.com/simbaja/ha_gehome/assets/72116866/26119547-9aaf-4bde-8c7a-cc345308aac5)

**Comment by tbfistere** [comment]
These are the logs I found.  There is a text file included due to the length of the log entry.

![Capture1](https://github.com/simbaja/ha_gehome/assets/77538187/a09b28f7-0cba-440a-ba02-d36af09caf49)
![Capture2](https://github.com/simbaja/ha_gehome/assets/77538187/7bb1df19-9629-4deb-a438-484844a0fcbf)
[Capture3.txt](https://github.com/simbaja/ha_gehome/files/11781229/Capture3.txt)

**Comment by techtim89** [comment]
I just updated the operating system to 10.3.  Still no change.  Bummer...

**Comment by simbaja** [comment]
So, that log file is basically going back to the login screen, perhaps they changed something on the login?  It may not be HA related, can you try it using the [SDK](https://github.com/simbaja/gehome) directly and see if it'll log you in?

**Comment by tbfistere** [comment]
I see there was an update in HACS today, I installed it and it appears to be resolved.  Thank you!

**Comment by piotroosh** [comment]
> I see there was an update in HACS today, I installed it and it appears to be resolved. Thank you!

I don't see HACS updates. I'm on 1.32.1.   I even reintstalled HACS.    GE integration still not working. ;(

**Comment by gsmalleus** [comment]
> > I see there was an update in HACS today, I installed it and it appears to be resolved. Thank you!
> 
> I don't see HACS updates. I'm on 1.32.1. I even reintstalled HACS. GE integration still not working. ;( Downgrading HA back to 2023.5.4 and it works again. So whatever was changed in 2023.6 makes this integration fail.

I am also on 1.32.1 and don't see a HACS update.  I have rolled back to 2023.5.4 where the integration is working as well.

**Comment by techtim89** [comment]
Any caveats for rolling back?  I've never rolled back an update.  Is that just done under "Settings, System, Backups".  Then choose the "core_2023 5.4" backup and click "Restore"?  Since HASS say's it's running 10.3 operating system, will that stay or need to be reverted also?  Thank you!

> > > I see there was an update in HACS today, I installed it and it appears to be resolved. Thank you!
> > 
> > 
> > I don't see HACS updates. I'm on 1.32.1. I even reintstalled HACS. GE integration still not working. ;( Downgrading HA back to 2023.5.4 and it works again. So whatever was changed in 2023.6 makes this integration fail.
> 
> I am also on 1.32.1 and don't see a HACS update. I have rolled back to 2023.5.4 where the integration is working as well.

**Comment by piotroosh** [comment]
I just do 
ha core update --version 2023.5.4
In terminal. 
no issues with downgrading in my case.

**Comment by techtim89** [comment]
Just saw and updated to 2023.06.2.  Still no joy…

**Comment by simbaja** [comment]
Any chance you have special characters in your password?  If so, can you remove them and try again?

**Comment by techtim89** [comment]
Tried resetting my password to take them out and it requires you to use special characters.

**Comment by techtim89** [comment]
> Tried resetting my password to take them out and it requires you to use special characters.

Ok, so the mobile app was requiring special characters but the website allowed me to reset it without.  Did that and tried to re-add the instance.  Sadly still getting the same error "! Failed to set up"

**Comment by simbaja** [comment]
can you post a full log?  and is there any chance you can run the SDK app using python 3.11?  It would be easier to diagnose if we can replicate the issue outside of home assistant

**Comment by techtim89** [comment]
I've never used python unfortunately.  Do you have any how to, step by steps I could use to try it?  Here's the log.


This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/ge_home/update_coordinator.py:174
Integration: GE Home (documentation)
First occurred: 2:18:29 PM (2 occurrences)
Last logged: 9:43:41 PM

Error setting up entry ********@gmail.com for ge_home
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 172, in async_setup
    await self.initialization_future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ge_home/__init__.py", line 45, in async_setup_entry
    if not await coordinator.async_setup():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ge_home/update_coordinator.py", line 174, in async_setup
    raise HaCannotConnect("Initialization timed out")
custom_components.ge_home.exceptions.HaCannotConnect: Initialization timed out

**Comment by techtim89** [comment]
This may be another error log.

Logger: homeassistant.config_entries
Source: helpers/entity_component.py:179
First occurred: 9:43:09 PM (9 occurrences)
Last logged: 9:43:09 PM

Error setting up entry ******@gmail.com for select
Error setting up entry ******@gmail.com for climate
Error setting up entry ******@gmail.com for light
Error setting up entry ******@gmail.com for button
Error setting up entry ******@gmail.com for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 169, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 179, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

**Comment by techtim89** [comment]
So I just went in and completely removed all files and folders for "ge_home" under the "custom_components" folder.  Then using the installer steps I added the repository, rebooted and logged in.  When doing so it finally all kicked back up!  WHOOP!  Looks good to go now!

**Comment by FoxRx** [comment]
I did the same thing as techtim89....ALL IS GOOD NOW!  Many thanks to all who worked on resolving this issue!!!

**Comment by simbaja** [comment]
If there's anyone else having this issue, please follow the steps described by @techtim89:

> So I just went in and completely removed all files and folders for "ge_home" under the "custom_components" folder. Then using the installer steps I added the repository, rebooted and logged in. When doing so it finally all kicked back up! WHOOP! Looks good to go now!

If that doesn't work, please post here, otherwise I'll assume that it's just a nuance of the upgrade process and close this issue.

**Comment by yellowcooln** [comment]
> I am having the same issue after updating to the following version:
> 
> Home Assistant 2023.6.1 Supervisor 2023.06.1 Operating System 10.2 Frontend 20230608.0 - latest
> 
> ![image](https://user-images.githubusercontent.com/12516003/244584448-a3007aee-57c8-4cca-953a-d7632609dd12.png) ![image](https://user-images.githubusercontent.com/12516003/244584513-737ea5fd-3445-491c-a2b8-48aa7bdcfe14.png)

I've upgraded to the following versions.

Home Assistant 2023.6.3 
Supervisor 2023.06.2 
Operating System 10.3 
Frontend 20230608.0 - latest 
RPi 4

I've entirely removed the ha_gehome folder from custom_components, rebooted HA, and reinstalled the v0.6.7 release into custom_components, I had to restart HA twice in order to get past "Please wait, starting configuration wizard for ge_home"

I now have devices again in HA! 

![image](https://github.com/simbaja/ha_gehome/assets/12516003/51501acb-1f9d-4806-a519-cfe1f1bba253)

_I'm not home it's why they are currently not on._

**Comment by piotroosh** [comment]
manually removed ha_gehome and reinstalled. Everything works.  yey. 
I tried to diff old vs new and honestly I couldn't find any differences that would break it. 
One thing I didn't check were the  file permissions.

**Comment by simbaja** [comment]
I'm going to close this issue, but have posted a pinned troubleshooting message to help with these steps.  Seems like it just needs to be re-installed to get things going again (no idea why).

**Comment by wtadler** [comment]
> > Tried resetting my password to take them out and it requires you to use special characters.
> 
> Ok, so the mobile app was requiring special characters but the website allowed me to reset it without. Did that and tried to re-add the instance. Sadly still getting the same error "! Failed to set up"

@techtim89, which website allowed you to reset your password without special characters? The only website I can find (https://geapp.my.site.com/GEA/s/mya-my-products) requires a special character, just like the app.
