### ISSUE TITLE
Support preheat status on Cafe oven (dual oven, in my case)

### ISSUE THREAD

**Issue by ex-nerd** [simbaja/ha_gehome#175]
It looks like this is being used in the Advantium setup but not the general oven info. I've run a test tests to confirm that pre-heat mode on my oven (both upper and lower) is simply reported as `Bake` both during and after preheat.

I pulled down `gehome` and ran the websocket example and it pulled down some logs, summarized here:

```
Setting ErdCode.UPPER_OVEN_COOK_MODE to Bake (350°)
received event: appliance_state_change, processing callbacks...
received event: appliance_update_received, processing callbacks...
Setting ErdCode.LOWER_OVEN_RAW_TEMPERATURE to 127
received event: appliance_state_change, processing callbacks...
received event: appliance_update_received, processing callbacks...
Setting ErdCode.UPPER_OVEN_RAW_TEMPERATURE to 274
received event: appliance_state_change, processing callbacks...
received event: appliance_update_received, processing callbacks...
Appliance state change detected in GeAppliance(REDACTED) (ErdApplianceType.OVEN). Updated keys: ErdCode.UPPER_OVEN_RAW_TEMPERATURE
Setting ErdCode.UPPER_OVEN_COOK_MODE to Bake (350°)
received event: appliance_state_change, processing callbacks...
received event: appliance_update_received, processing callbacks...
Appliance state change detected in GeAppliance(REDACTED) (ErdApplianceType.OVEN). Updated keys: ErdCode.UPPER_OVEN_COOK_MODE
Setting ErdCode.UPPER_OVEN_DISPLAY_TEMPERATURE to 274
received event: appliance_state_change, processing callbacks...
received event: appliance_update_received, processing callbacks...
Appliance state change detected in GeAppliance(REDACTED) (ErdApplianceType.OVEN). Updated keys: ErdCode.UPPER_OVEN_DISPLAY_TEMPERATURE
Setting ErdCode.UPPER_OVEN_CURRENT_STATE to Preheat
received event: appliance_state_change, processing callbacks...
```

This suggests that `gehome` (or at least the latest version in git) supports `preheat`, but whatever I have with `ha_gehome=v0.6.7` does not. I don't see any new git changes since `v0.6.7` so I suspect it's missing something.

I'm happy to submit this as a pull request, but I don't even know where to begin to figure out what is/isn't making its way into the ha plugin.

**Comment by simbaja** [comment]
I think I'm a little confused on this, seems like turning it on to "Bake" is the solution?  If you're just looking for something to say "Preheat", I think all that is needed is to add a new sensor for the UPPER_OVEN_CURRENT_STATE code (and presumably the lower equivalent).

**Comment by ex-nerd** [comment]
When I turn the oven on to any mode (e.g. `Bake`) it goes into a preheat mode. You can see this in the logs above. This state is not reflected in Home Assistant, which just shows the oven in `Bake` even while it is preheating.

The goal for this would be to have a sensor that detects when preheating is done. The oven has an incredibly silent beep, and my wife is often not near her phone (which gets a push notification from the official app), so I'd like to set up an automation to perform some other alert.

I'm also seeing some issues like `ErdCode.LOWER_OVEN_COOK_TIME_REMAINING` (another way-too-quiet alert from the oven when that reaches zero) coming through properly on the web socket but not making it into Home Assistant, so that may also be a related missed signal.

**Comment by simbaja** [comment]
Added the oven state sensor referenced in your original debug message.  LOWER_OVEN_COOK_TIME_REMAINING is already present in HA, so if you're having an issue with that, please open a new issue and provide some debug logs of what you're seeing there.

**Comment by ex-nerd** [comment]
Thanks for fixing the missing `LOWER_OVEN_COOK_TIME_REMAINING` but that is a separate issue. This issue was about the lack of `Preheat` status. See the log message in the original post referencing `Setting ErdCode.UPPER_OVEN_CURRENT_STATE to Preheat`

I've enabled debug logging in Home Assistant and there is no reference to `UPPER_OVEN_CURRENT_STATE` (or the lower oven equivalent) when I turn the oven on/off.

I'm unable to reopen this issue but would rather not file a separate duplicate unless you request it.

**Comment by ex-nerd** [comment]
Never mind. This is me getting confused again about terminology. I'm used to `master / stable` or `dev / main` for brach naming conventions. I see now that the change is present on the `dev` branch and the `v0.6.8-dev6` tag … and the preheat status is now showing in home assistant:

<img width="329" alt="Screenshot 2023-08-03 at 5 08 00 PM" src="https://github.com/simbaja/ha_gehome/assets/154074/6023c960-d147-41f8-bd36-f9fe5af411b6">

**Comment by advisorgee** [comment]
I have a Cafe dual oven as well and have installed the latest version, but I do not see Preheat as the current state, I still see whatever the current mode is (ie. Frozen Pizza). This happens on both ovens

**Comment by ex-nerd** [comment]
> I do not see Preheat as the current state

This was working for me on `v0.6.8-dev6` and I just updated to `v0.6.8` and see that it still works with regular cooking. However, the special modes (that "baked goods" mode is amazing for 🍪) don't show a separate preheat state (in HA or the logs) even though the official app can. Maybe we need to file a new bug? Probably run some tests with the websocket example program to see what codes are being sent and missed.

**Comment by advisorgee** [comment]
You are correct; regular cooking shows Preheat but the other specialty modes show the mode title. I'll take a look at that websocket example program to see if I can figure it out.

**Comment by ex-nerd** [comment]
> I'll take a look at that websocket example program to see if I can figure it out.

let me know if you need a beta tester
