### ISSUE TITLE
SmartHQ + Home Assistant, let’s Debug our Digital Dilemmas

### ISSUE THREAD

**Issue by JaredHatfield** [simbaja/ha_gehome#176]
Hi, I’m Jared a Senior Principal Platform architect at GE Appliances and helped build the SmartHQ cloud APIs and am familiar with how they work, but I’m just now starting to learn about Home Assistant.

We noticed that this project is a Home Assistant integration for GE Appliances SmartHQ enabled products.  That’s awesome! We would love to collaborate more on this.

GE Appliance’s does not have a lot of experience with Home Assistant but are wanting to learn more. 

We have also noticed that this integration is having some issues https://github.com/simbaja/ha_gehome/issues/171 and would like to help with resolving those. 

Additionally, we have some initial ideas on how we can collaborate:
 - We can make a dedicated OAuth 2.0 app just for this project.
 - Provide API documentation for easier and more reliable integration (we have newer APIs that are easier to use).

If you are interested, we’d like to set up a call to connect with some of our developers. What is the best way for us to collaborate on this?

**Comment by simbaja** [comment]
Nice to hear from you and would be interested in collaborating.  If you provide your email or check the git commits for mine, we can get the call scheduled and start working together.

**Comment by thomasmaxson** [comment]
Enhancement idea: Using the built in Bluetooth to send data to Home Assistant. Ditch the cloud requirement.
