### ISSUE TITLE
Home assistant updated and now no devices.

### ISSUE THREAD

**Issue by JustinTomerlin** [simbaja/ha_gehome#177]
It seems that after I updated my home assistant to the newest version, my window unit was no longer being picked up. In an attempt to resolve the issue, I decided to remove my account and re-add it. However, I am now facing a problem where no devices are being found, even though the window unit is present in my smart HQ account.

**Comment by JustinTomerlin** [comment]
I found these in the log if they help 

Logger: gehomesdk.clients.base_client
Source: runner.py:179
First occurred: 4:46:15 PM (110 occurrences)
Last logged: 5:00:30 PM

Error refreshing authentication: Connection closed


Log Details (WARNING)
This error originated from a custom integration.
Logger: custom_components.ge_home.update_coordinator
Source: custom_components/ge_home/update_coordinator.py:237
Integration: GE Home ([documentation](https://github.com/simbaja/ha_gehome))
First occurred: 4:51:34 PM (19 occurrences)
Last logged: 5:00:19 PM

could not reconnect: Problem with request, code: 403, will retry in 7.5 seconds
could not reconnect: Connection closed, will retry in 7.5 seconds
could not reconnect: Connection closed, will retry in 15 seconds
could not reconnect: Problem with request, code: 403, will retry in 15 seconds
could not reconnect: Problem with request, code: 403, will retry in 30 seconds

**Comment by JustinTomerlin** [comment]
Did not mean to close it

**Comment by greenship24** [comment]
FWIW a code 403 means invalid auth. I would doublecheck your username and password.

**Comment by bengarding** [comment]
I've been having the same issue with my washer and dryer. I have similar logs with the 403 code. I've triple checked that my credentials are correct

**Comment by JustinTomerlin** [comment]
> I've been having the same issue with my washer and dryer. I have similar logs with the 403 code. I've triple checked that my credentials are correct

**Comment by JustinTomerlin** [comment]
> I've been having the same issue with my washer and dryer. I have similar logs with the 403 code. I've triple checked that my credentials are correct

Did you ever find a fix? Still having the same issue

**Comment by bengarding** [comment]
Nope, never figured out the fix

**Comment by simbaja** [comment]
I would suggest trying the SDK application directly, it might be able to give you more information as to why you're getting the 403 error.  I'd suspect the region might be incorrect, but I haven't seen this issue, so hard to diagnose without additional logs.

**Comment by bengarding** [comment]
I recently took another crack at this and after updating the integration in HACS to the latest version, everything went back to working normally

**Comment by simbaja** [comment]
I'm going to close this assuming that the latest pre-release fixes the issues.  Please let me know if it does not and I can reopen.
