### ISSUE TITLE
individual element control on ranges?

### ISSUE THREAD

**Issue by groovejumper** [simbaja/ha_gehome#178]
Sorry if this isn't the right place, this isn't really an issue...  We use this integration with our washer & dryer, and have a few automations set up (light pattern on the back porch after dark when HA knows we're out there, and the washer or dryer cycle finishes, things like that).

Now it seems we need a new slide-in range.  Are there any models that allow for individual element control?  Use case would be, if a back element has been on for more than 30 minutes and we haven't added a timer, turn it off.  If a front element has been on for more than 20 minutes, turn it off.  Set individual timers for specific elements.  That sort of thing.

I've searched around and setting oven temperatures and turning on/off seems possible, but I can't seem to find any details about stove-top elements.

**Comment by simbaja** [comment]
Unfortunately not from what I can tell.  I'm guessing it's a safety issue - they don't want you to control something hot that isn't contained remotely.  It would be nice if they at least let you turn it off, but I haven't seen that at all.
