### ISSUE TITLE
Support for GE Profile 2-in-1 washer/dryer (PFQ97HSPVDS)?

### ISSUE THREAD

**Issue by StephenShamakian** [simbaja/ha_gehome#185]
Does this HA integration work with GE Profile 2-in-1 washer and dryer units like the PFQ97HSPVDS? I see on the readme it mentions "Laundry (Washer/Dryer)" so I'm assuming it does? But not sure if a combo unit would report in differently?

I don't have one of these units yet, but if I were to get one, I'm trying to do research as to if HA would be able to communicate with it.

**Comment by manedfolf** [comment]
@StephenShamakian I have a unit I got today and I'm preparing to test it. I'll try to report back.

**Comment by manedfolf** [comment]
It appears to work and shows up like this with its default configuration. It has different elements for the washer and dryer. I have not tested it extensively yet, but I am trying to build a notification system to notify different roommates when their own laundry is done.

![image](https://github.com/simbaja/ha_gehome/assets/41547235/6f376447-2ae3-4009-856b-286806e75a83)

**Comment by StephenShamakian** [comment]
> It appears to work and shows up like this with its default configuration. It has different elements for the washer and dryer. I have not tested it extensively yet, but I am trying to build a notification system to notify different roommates when their own laundry is done.
> 
> ![image](https://user-images.githubusercontent.com/41547235/259235238-6f376447-2ae3-4009-856b-286806e75a83.png)

Great news! Thanks for confirming those details for me!
