### ISSUE TITLE
Request to add new WiFi DeHumidifier AWHR50LB

### ISSUE THREAD

**Issue by jerflash** [simbaja/ha_gehome#188]
GE has just come out with a smart wifi dehumidifier. I already had a GE Wifi window AC working though this addon and it works great.

The new dehumidifier sets up under the AC tab in the smartHQ app so even they concider it an AC. 

Could you look into adding this? 

Thanks!

**Comment by simbaja** [comment]
Can you check the latest pre-release and see if it does what you're looking for?

**Comment by httr-1991** [comment]
I just setup 0.67 and I have AWHR50LB in my Smart HQ app and I dont see any entities in HA under GE Home. Is there something I should try to get it working?

**Comment by jerflash** [comment]
> Can you check the latest pre-release and see if it does what you're looking for?

Hey sim,

sorry I missed this super fast reply… email settings. 

I will have to check the next time I’m at the property which is early October. Until then I’m happy to see someone else has it to test

**Comment by jerflash** [comment]
> I just setup 0.67 and I have AWHR50LB in my Smart HQ app and I dont see any entities in HA under GE Home. Is there something I should try to get it working?

It seems sim may have added this in a prerelease which is 0.68 and now has a 5th version. 0.68 DEV5

give it a try because I don’t have access to that unit since it is at another property.

**Comment by httr-1991** [comment]
on 0.68-Dev5 is looks to be working!

I see 5 sensors
![image](https://github.com/simbaja/ha_gehome/assets/121140889/1e3736de-7850-4a88-8bb4-3e5363a7f99e)

And 2 controls (On/Off, Target Humidity)
![image](https://github.com/simbaja/ha_gehome/assets/121140889/58ed3d9e-2b4d-48a4-b5e8-8cae4dd88e63)

**Comment by jerflash** [comment]
thats awesome! do you have homekit? If so does HA send anything over to it?

**Comment by httr-1991** [comment]
sorry, dont have it

**Comment by httr-1991** [comment]
ok, I have a request, is the 'Estimated Energy Usage' able to be exposed. It's in the Smart HQ app. It would be very helpful to track how much energy devices are using.

**Comment by simbaja** [comment]
If you can identify how to read that from the raw data, happy to add it.

**Comment by httr-1991** [comment]
if there is a tutorial on how to do that, i can try.

**Comment by jerflash** [comment]
Hey I forgot to write in but I upgraded to this version and the dehumidifier does indeed show up in homekit and is controlable. works great thanks!

**Comment by simbaja** [comment]
Going to close this, @httr-1991, if you get some information on how to add the energy, please feel free to open a new issue and we can work through that.
