### ISSUE TITLE
Home Assistant Log "gehomesdk.erd.converters.specialized.erd_unit_type_converter"

### ISSUE THREAD

**Issue by rob7419** [simbaja/ha_gehome#189]
I have search through the issues and didn't find this specific one reported. All the other that I have found referred to an individual appliance and I'm not sure what the "specialized" is referencing. I have a refrigerator, washer, and dryer connected through the integration. 

Logger: gehomesdk.erd.converters.specialized.erd_unit_type_converter
Source: runner.py:179
First occurred: 8:49:45 AM (117 occurrences)
Last logged: 9:47:15 AM

Unknown Unit Type: {value}, using default

I have enabled debug logging and restated HA, been running for about 2hours and no other logs are set. Only thing is the occurrences count increases with time.

**Comment by simbaja** [comment]
Nothing really problematic, it's not used within the Home Assistant component.  I've gone ahead and fixed it so it should only show up once, and I'll get it into the next version.
