### ISSUE TITLE
Support for GE window air conditioners

### ISSUE THREAD

**Issue by swcrawford1** [simbaja/ha_gehome#19]
Would be very nice to have.

**Comment by simbaja** [comment]
We can certainly try to tackle that next, but we'll need some assistance with confirming functionality as we're essentially reverse engineering the protocols by trial and error in many cases.  The first step is to head on over to the sdk repository, clone it, run it, and post the debug log (just the section dealing with the AC unit, you'll see it in there) into a new issue there.  We'll probably have to do some back and forth to figure things out afterwards.

After we get the underlying support built in, we can then get support built into the HA component.

**Comment by swcrawford1** [comment]
I'd love to try but I'm unsure how. Can you give some broad instruction for
doing this?
Thanks in advance

**Comment by simbaja** [comment]
We're working on getting a wiki put together, but in the meantime, hopefully this post helps: https://github.com/simbaja/ha_components/issues/12#issuecomment-873649462.

Basically, you'll need to download and run the code from the simbaja/gehome repo and copy/paste the log out.  That should give us enough information to get started.

**Comment by swcrawford1** [comment]
Following the instructions you linked to I get an error about 'setup.py' not being found. Any idea what I'm doing wrong?

**Comment by simbaja** [comment]
Is your current path at the root of the repo (i.e. there should be a setup.py in the directory you're running that command from).  If not, you'll need to switch to that directory and try it from there.

**Comment by swcrawford1** [comment]
Sorry to be so difficult. I have tried obtaining the repo through git using
this url:
https://github.com/simbaja/ha_gehome.git
and also via downloading a zip file. In both cases I don't see a setup.py
anywhere in the directory structure. Does it get created by some process
I'm not aware of?
Thanks in advance for your help, I really would like to get this working.

**Comment by simbaja** [comment]
@swcrawford1, @mbrentrowe:  I've added initial support for these units in the "dev" branch.  Can you pull it down and install into HA and let me know how it works (and where I messed up)?

**Comment by mbrentrowe** [comment]
Yep, I got pulled into work but will test it out this evening.

**Comment by mbrentrowe** [comment]
I'm getting an error of Config flow could not be loaded when I try to add the integration. This is the error in my HA logs.

Logger: homeassistant.config_entries
Source: config_entries.py:698
First occurred: 6:48:20 PM (1 occurrences)
Last logged: 6:48:20 PM

Error occurred loading configuration flow for integration ge_home: cannot import name 'ApplianceApi' from partially initialized module 'custom_components.ge_home.devices' (most likely due to a circular import) (/config/custom_components/ge_home/devices/__init__.py)

**Comment by simbaja** [comment]
Try now, had a circular reference in there, hopefully I got it.

**Comment by mbrentrowe** [comment]
That fixed it. Only two issues I can see so far. One is small, the operation that is title Auto is Eco on the unit and app. Not really a big deal.

I was able to do all controls except for powering it on from an off state. I can change modes and temperatures fine and also turn it off, but it won't turn back on. I tried to do this by changing the operation from off to any other state and also by using the power button in the thermostat card.

**Comment by simbaja** [comment]
Fantastic!  The first issue is something I can't fix, it's a limitation of HA (has to be one of the modes listed here https://developers.home-assistant.io/docs/core/entity/climate/).  I mapped it as well as I could.

For the second issue, I think I can make an adjustment that'll fix it.  Can you try the switch that I also put out there (it'll be outside the thermostat entity).  If that works, I can make some adjustments in the climate control to turn it on if needed.

Almost there!

**Comment by mbrentrowe** [comment]
No dice with that switch. Same error when trying to turn off or on with it.

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/ge_home/entities/common/ge_erd_switch.py:20
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 7:34:30 PM (1 occurrences)
Last logged: 7:34:30 PM

[140297704228032] 'bool' object has no attribute 'value'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 856, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/ge_home/entities/common/ge_erd_switch.py", line 20, in async_turn_on
    await self.appliance.async_set_erd_value(self.erd_code, True)
  File "/usr/local/lib/python3.9/site-packages/gehomesdk/ge_appliance.py", line 150, in async_set_erd_value
    erd_value = self.encode_erd_value(erd_code, value)
  File "/usr/local/lib/python3.9/site-packages/gehomesdk/ge_appliance.py", line 127, in encode_erd_value
    return self._encoder.encode_value(erd_code, value)
  File "/usr/local/lib/python3.9/site-packages/gehomesdk/erd/erd_encoder.py", line 91, in encode_value
    return self._registry[erd_code].erd_encode(value)
  File "/usr/local/lib/python3.9/site-packages/gehomesdk/erd/erd_configuration.py", line 24, in erd_encode
    return self.converter.erd_encode(value)
  File "/usr/local/lib/python3.9/site-packages/gehomesdk/erd/converters/specialized/erd_on_off_converter.py", line 13, in erd_encode
    return value.value
AttributeError: 'bool' object has no attribute 'value'

**Comment by simbaja** [comment]
OK, let me look into that... looks like my encoder isn't quite right.  Shouldn't take too long to fix though.

**Comment by simbaja** [comment]
Ok, give them both a shot now, hopefully it works.  The on/off functionality wasn't documented as available based on the HA documentation, but when I looked at the source, I figured out how to make that work too (hopefully).

**Comment by mbrentrowe** [comment]
That fixed it. I can turn it from off to another state now. Did you mean to remove the switch entity? I don't really think I'd need it but just curious.

**Comment by simbaja** [comment]
No, I didn't mean to do so, but I see why it disappeared.  I might spend a little time to make the switch a little more generic, the initial version only worked with bools, but I think we'll want it to work with multiple types.  I'll get that into the next commit to the dev branch.

Besides the switch disappearing, everything else looks good?

**Comment by simbaja** [comment]
Switch should be back now (and hopefully working as well)

**Comment by mbrentrowe** [comment]
Everything is working great. I'll pull the latest dev build tomorrow to test the switch functionality.

**Comment by mbrentrowe** [comment]
Switch is working as expected now.

**Comment by simbaja** [comment]
@mbrentrowe, can you post a screenshot of the climate control?  Want to add it to the readme file.  Thanks for your help confirming it all works for you!

@swcrawford1, can you confirm the new functionality is working for you as well?

**Comment by mbrentrowe** [comment]
Sure, let me know if this works.

![image](https://user-images.githubusercontent.com/25138198/128640978-738ec06c-a24d-42f7-b0e4-105f8f1b38d4.png)

![image](https://user-images.githubusercontent.com/25138198/128640981-ad771d9e-fcd1-4308-a924-92c750edd099.png)

**Comment by swcrawford1** [comment]
Seems to be working for me. Added a thermostat card and tested the auto,
cool, fan only, and power off functions. Awesome work, Thanks!

**Comment by Garulf** [comment]
Wow amazing work! Just wanted to ask what "Wac Demand Response Power" represents? Is this some sort of kWh or W sensor?

**Comment by simbaja** [comment]
No idea, it looked like a percentage of some sort, the formula in the app for interpreting it is value / 1000 - could be W or something though.  I don't actually have one of these devices so I can't test on my own, I just exposed everything that was available.

**Comment by Garulf** [comment]
> No idea, it looked like a percentage of some sort, the formula in the app for interpreting it is value / 1000 - could be W or something though.  I don't actually have one of these devices so I can't test on my own, I just exposed everything that was available.

Ah! That's definitely the kWh. kWh is `(W * hours) / 1000`.

**Comment by simbaja** [comment]
Yep, I'll make that change, and also change the interpretation in the SDK, thanks for the help in identifying that!

**Comment by Garulf** [comment]
> Yep, I'll make that change, and also change the interpretation in the SDK, thanks for the help in identifying that!

No problem, glad to help!

Also with the new Energy Dashboard in [Home Assistant 2021.8.0](https://www.home-assistant.io/blog/2021/08/04/release-20218/)
We should probably set the `state_class` of this sensor to [`measurement`](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)

**Comment by simbaja** [comment]
Interesting... I will have to look into that, probably applies to multiple sensors in here.

**Comment by simbaja** [comment]
I've changed it in the newest dev version to "power" instead of energy, it looked like it was more an instantaneous value instead of a value over time.  Let me know if that doesn't seem to work right.  I'll add the `state_class` stuff in a little bit, want to get this version stable for everyone first.

**Comment by Garulf** [comment]
> I've changed it in the newest dev version to "power" instead of energy, it looked like it was more an instantaneous value instead of a value over time. Let me know if that doesn't seem to work right. I'll add the `state_class` stuff in a little bit, want to get this version stable for everyone first.

Yeah, power is the correct `device_class` I knew something was slightly off.
