### ISSUE TITLE
Log showing "ValueError ErdCode.WIFI_MODULE_UPDATING - 0A"

### ISSUE THREAD

**Issue by tmugan** [simbaja/ha_gehome#190]
I am seeing this within the Log files on HASS.
Haier Washing Machine Model HWF95AN1

The Washer is often losing the pairing within Android app so wondering if this is related or indicative of something I need to fix?

---------------------------------------------

Logger: gehomesdk.erd.erd_encoder
Source: runner.py:179
First occurred: 11:12:21 AM (498 occurrences)
Last logged: 3:22:39 PM

Got ValueError ErdCode.WIFI_MODULE_UPDATING - 0A

**Comment by simbaja** [comment]
I think the latest version should resolve this error for you, but let me know if you see otherwise
