### ISSUE TITLE
Integration stopped communicating with Device

### ISSUE THREAD

**Issue by lightdsn** [simbaja/ha_gehome#199]
HI, I have a range hood connected that had been working well but currently isn't communicating with the device and updating it's status. I reloaded the configuration but still no change. Any ideas?

**Comment by simbaja** [comment]
Are there any messages in the log?

**Comment by simbaja** [comment]
I would advise trying 0.6.9-dev4 or above (or the final 0.6.9 release when ready).  If you are still exhibiting issues, we can reopen the issue and work towards resolution.
