### ISSUE TITLE
Water Softener Support 

### ISSUE THREAD

**Issue by DrJeff** [simbaja/ha_gehome#20]
What do I need to do to get the water softener setup?
Model GXSHC40N it shows in the phone app but not HA yet. :)

~~Where is this SDK repository that will offer debug?~~ Nevermind I see and will post what I find

**Comment by simbaja** [comment]
Glad you found the sdk!  I think a debug log would be useful to get us started for the water softener.  We'll probably want to open an issue in the gehome repository so that we can go back and forth as we figure out what all the codes do.

**Comment by Awk34** [comment]
@simbaja how would one collect a debug log?

**Comment by simbaja** [comment]
@Awk34, my apologies, this slipped through.   Basically, you'd go to https://github.com/simbaja/gehome, pull the repo down, create the credentials.py file, then run the websocket_example.  It'll output the low-level details that we can use to figure out the available controls and sensors.

I've been working with @npentell on issue #57, and we're making progress there.  I'm going to close this issue, feel free to comment over on that issue, a second user is definitely useful to figure out if we've got everything.  Hopefully, this will be in the integration soon, sorry for the delays, work has been crazy busy.
