### ISSUE TITLE
Water Filter Unit Conversion Issues

### ISSUE THREAD

**Issue by KyleStilkey** [simbaja/ha_gehome#205]
Looks like you're using a method that's being removed from Home Assistants.

```
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:232
Integration: Sensor ([documentation](https://rc.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 4:45:10 PM (1 occurrences)
Last logged: 4:45:10 PM

The unit of sensor.fdpoek5u01973_wh_filter_day_usage (gal) cannot be converted to the unit of previously compiled statistics (g). Generation of long term statistics will be suppressed unless the unit changes back to g or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
```

**Comment by simbaja** [comment]
The old unit of measurement (g) was incorrect and replaced with the correct one (gal), per https://developers.home-assistant.io/docs/core/entity/sensor/.  Unfortunately, what that message is saying is that you have statistics in the old unit of measure that they can't convert (grams -> gallon is not a valid conversion).  I think you'll have to delete the statistics somehow, but I couldn't find a great way to do that other than purging the database.
