### ISSUE TITLE
Laundry Time Remaining

### ISSUE THREAD

**Issue by Madbeefer** [simbaja/ha_gehome#208]
I have a GE profile washer and dryer, everything seems to work pretty well, with the exception of the time remaining entities. It seems to work OK when something is in the machines being washed or dried. But when they are not in use the seem to indicate the time remaining is what the previous cycle run time was.

**Comment by simbaja** [comment]
That's unfortunately the way it's reported by the underlying device.  I think that you can probably just create a template sensor that sets to some other value when it's not actually running.  From my recollection, that's what the official app does for its display.  Hope that helps!

**Comment by Shayne55434** [comment]
If it helps, I created the following template:
![image](https://github.com/simbaja/ha_gehome/assets/37595910/ec1c451e-95ac-4266-8807-d2c7d2810863)

sensor.washer_minutes_remaining

```yaml
{% if states('sensor.washer_machine_state') | lower not in ['off', 'unknown', 'unavailable', 'none'] %}
  {% set parts = states('sensor.washer_time_remaining').split(':') %}
  {{ (parts[0] | int * 60) + parts[1] | int }}
{%- else -%}
  0
{%- endif -%}
```

**Comment by Madbeefer** [comment]
Awesome, thanks I will give it a test drive.
