### ISSUE TITLE
"Unknown error reading socket" causing the integration to become unresponsive.

### ISSUE THREAD

**Issue by tfberg** [simbaja/ha_gehome#211]
Thanks for the integration. It works well until the error is encountered. Deleting and re-adding the integration restores device availability and responsiveness. Unfortunately, the error reoccurs after a an hour or so.

From the log:

Logger: gehomesdk.clients.websocket_client
Source: runner.py:188
First occurred: 12:10:17 AM (8 occurrences)
Last logged: 12:10:18 AM

File "/usr/local/lib/python3.11/site-packages/gehomesdk/ge_appliance.py", line 136, in get_erd_value

**Comment by simbaja** [comment]
1) What version are you running?  If you aren't on the pre-release 0.6.9-dev4, can you try that version?
2) Can you provide a full log

**Comment by tfberg** [comment]
Thanks for the quick reply. I have installed pre-release 0.6.9-dev4 and it is working thus far. Will provide more feedback tomorrow.

**Comment by tfberg** [comment]
No errors since I updated to pre-release 0.6.9-dev4 and the integration has maintained responsiveness. Seems that the issue has been resolved. Thanks much for the quick fix and great integration!
