### ISSUE TITLE
Support for GE Profile Cooktop (PEP7036DTBB)

### ISSUE THREAD

**Issue by csobrinho** [simbaja/ha_gehome#216]
Hi, I have this [cooktop](https://www.geappliances.com/appliance/GE-Profile-36-Built-In-Touch-Control-Electric-Cooktop-PEP7036DTBB) and a [GE Profile Dual Wall Oven (JKD5000SNSS)](https://www.geappliances.com/appliance/GE-27-Smart-Built-In-Convection-Double-Wall-Oven-JKD5000SNSS).

The Oven shows up, both of them: temp, remote enabled, lights, mode, user offset, etc. All the sensors, entities, bells and whistles but the cooktop does not.

My guess is that this model probably uses similar communication as other models but is not part of some allow list or is missing some mapping to a capability list?

I'm happy to provide info, debug logs, even a potential PR but I'm not sure where to start. I have read the troubleshoot section but couldn't find a good place with some info on how to capture logs, try the python integration locally before we start exposing this info to HA.

In sum, very eager and happy to help but not sure where to start.

Thank you for all you do for this integration!

**Comment by simbaja** [comment]
If you head over to https://github.com/simbaja/gehome, you'll see a way to install the raw SDK and run an application that can capture the debug information.  I think that'll probably point us in the right direction.

**Comment by simbaja** [comment]
Feel free to head to the SDK if you have some time to provide debug information, closing here.
