### ISSUE TITLE
Multiple deprecated constants which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by JasonMeudt** [simbaja/ha_gehome#218]
Multiple deprecated constants used in GE Home will be removed in forthcoming HA versions.

See below:

Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 9:04:03 AM (26 occurrences)
Last logged: 9:04:03 AM

DEVICE_CLASS_HUMIDITY was used from ge_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.HUMIDITY instead, please report it to the author of the 'ge_home' custom integration
TEMP_FAHRENHEIT was used from ge_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please report it to the author of the 'ge_home' custom integration
TEMP_CELSIUS was used from ge_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'ge_home' custom integration
DEVICE_CLASS_POWER_FACTOR was used from ge_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.POWER_FACTOR instead, please report it to the author of the 'ge_home' custom integration
DEVICE_CLASS_TEMPERATURE was used from ge_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.TEMPERATURE instead, please report it to the author of the 'ge_home' custom integration

**Comment by simbaja** [comment]
Should be resolved as of 0.6.10-dev0 (most of it is in 0.6.9, but missed a couple there).  Closing for now, but let me know if you see anything else that needs to be changed.
