### ISSUE TITLE
not a valid add-on repository?

### ISSUE THREAD

**Issue by andrewbpark** [simbaja/ha_gehome#220]
Tried to add the custom repo to HA and I'm getting this error: https://github.com/simbaja/ha_gehome is not a valid add-on repository

**Comment by simbaja** [comment]
Are you trying to add through HACS?

**Comment by dansauve** [comment]
I'm getting this same error today, on latest version of HA. @simbaja Am I doing something wrong?

<img width="595" alt="image" src="https://github.com/user-attachments/assets/e46447b0-6d1b-4ca3-9d5a-1385f9015d51">

I'm running HA in Hyper-V on Windows 10

Thanks
