### ISSUE TITLE
Integration stuck at initializing and then error.

### ISSUE THREAD

**Issue by fugs5** [simbaja/ha_gehome#222]
I added the integration to my home assistant. I put in my credentials which are the same credentials i use for SmartHQ. After confirming credentials, it's status is stuck on Initializing for about 10 minutes and then I see this error: Failed setup, will retry. It will do this a few times before it stops retrying. On SmartHQ I have a washer and Dryer and i have relogged on the app just to make sure i am typing the correct credentials.

I am using:
Home Assistant 2024.1.4
HACS 1.33.0
ha_gehome v0.6.8

When I enable Debug Logging, I get this error (My actual email address is in the error but i took it out for this post):

Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 10:27:16 AM (20 occurrences)
Last logged: 10:32:30 AM
 
Error setting up entry [Email Address] for climate
Error setting up entry [Email Address] for light
Error setting up entry [Email Address] for button
Error setting up entry [Email Address] for number
Error setting up entry [Email Address] for humidifier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 238, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 188, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

**Comment by fugs5** [comment]
Forgot to add this to original post.
I am using:
Home Assistant 2024.1.4
HACS 1.33.0
ha_gehome v0.6.8

**Comment by simbaja** [comment]
Can you take a look at the steps in https://github.com/simbaja/ha_gehome/issues/183 and see if it resolves anything?

**Comment by fugs5** [comment]
I did #183 but it still didnt work. As a last ditch effort, i installed using the Manual way instead of using HACS and this worked. Dont ask me why... lol
