### ISSUE TITLE
Add "Remote start" to GE dishwasher

### ISSUE THREAD

**Issue by Princesscleavage** [simbaja/ha_gehome#224]
Might it be possible to add "remote start" detection for GE dishwasher units? This functionality is enabled by opening the dishwasher drawer and holding the wifi button for three seconds the you are able to remote start the dishwasher from mobile app, it would be great to have this feature available in your HA device for automation of dishwasher when solar is producing power.
Thanks for the consideration

**Comment by dhi20** [comment]
I'd also be keen on this, Happy to provide logs.

**Comment by simbaja** [comment]
If you go to the SDK (https://github.com/simbaja/gehome) and run the application, you might be able to find the ERD that controls remote start.  Closing this issue to combine with #203, we can continue there as I believe it's the same topic, just a different product line.
