### ISSUE TITLE
Refrigerator door not showing open door

### ISSUE THREAD

**Issue by heyandy1st** [simbaja/ha_gehome#225]
I have a GE PVD28BYNFFS which has the French doors, center drawer and freezer drawer, but in addition it has the "quick access" door to just get to things on the left door.   When either French door, center tray, or freezer door open, the plugin is showing the door open, but when I open the "quick access" door, it does not get triggered.  The light inside comes own, and if I leave that door open the door open warning goes off...   
Not that big of a deal, just wondering if maybe something "off" for a fridge with quick access.

If you need any info let me know..  I am a developer (ok, now I spend most of my time in meetings as I moved more toward "architect" too many years ago!..  Also mostly C#, but I have done a little playing around with Python.  Very familiar with API's and all that fun stuff, but obviously not directly much with HA or GE stuff...)

**Comment by simbaja** [comment]
If you head over to the SDK repo (https://github.com/simbaja/gehome), you can run an application that report on changes to the values returned by the API.  If you attempt to open/close the quick access door, you should be able to see the code that changes, and then from there we can follow it through to potentially add it into the code.
