### ISSUE TITLE
Time Remaining not Going to Zero

### ISSUE THREAD

**Issue by magaman** [simbaja/ha_gehome#231]
We would like to add a timer to our dashboard but it seems the time remaining for both the Washer and Dryer never reaches zero and then the time just remains stuck at some number of seconds remaining. Any thoughts?

**Comment by simbaja** [comment]
I think that this might be unsolvable using the existing API.  Feel free to attach a debug log (use the SDK repository at simbaja/gehome) around the completion time period to see if there is something that shows up, but I'm not hopeful.
