### ISSUE TITLE
 Could not find appliance D828C99CE098 in known device list

### ISSUE THREAD

**Issue by gravelfreeman** [simbaja/ha_gehome#237]
For some reason my integration started complaining and throwing this error in the logs every now and then.

I don't know where this is coming from since my appliance ID is different. Also I can't find any entities for `D828C99CE098`.

![image](https://github.com/simbaja/ha_gehome/assets/44218371/cb8b870c-f2f3-436a-a80c-df200d5b09c5)

```python
2024-03-04 20:26:39.930 WARNING (MainThread) [custom_components.ge_home.update_coordinator] Could not find appliance D828C99CE098 in known device list.
```

I would like to get rid of this annoying error, thank you!

**Comment by jbonzey** [comment]
I get the same error for an unknown reason.  
![IMG_2491](https://github.com/simbaja/ha_gehome/assets/23142693/80f812d0-1b4d-4874-a456-4480da14c2eb)

**Comment by RobX82** [comment]
I am experiencing the same issue with my washer and dryer as well.

**Comment by rnotley** [comment]
I see the same error message, different device ID.  I have a GE Oven.

**Comment by simbaja** [comment]
This is normal, at some point I can change it to info level but it's not a high priority.  Feel free to submit a PR on it if you'd like.
