### ISSUE TITLE
How to remove old appliance

### ISSUE THREAD

**Issue by cfairbanks12** [simbaja/ha_gehome#238]
My GE washer died last week and my local dealer replaced it yesterday.  I deleted it in SmartHQ but it’s still showing up in HA.  I see how I can disable a device in the integration but I don’t see how to remove it though.

**Comment by simbaja** [comment]
I think that you might have to edit the json files directly in .storage folder (wouldn't advise if you don't have experience).  It might also be possible to remove all the entities (which would show as unavailable anyway) and that may remove the device too.
