### ISSUE TITLE
Fridge Drawer Mode displays N/A

### ISSUE THREAD

**Issue by CWSites** [simbaja/ha_gehome#243]
First off, thank you so much for your work on this. I can't express how awesome it is to have an integration for GE appliances!

Everything is working great except for my fridge drawer mode. In the HA app it shows "N/A" for each of the options (screenshot)

<img width="335" alt="Screenshot 2024-04-07 at 12 16 45 PM" src="https://github.com/simbaja/ha_gehome/assets/1242102/b0ce6285-d839-4e92-8102-a509c8f1ec8f">

Here are the options as displayed in the GE app (screenshot)

![IMG_7442](https://github.com/simbaja/ha_gehome/assets/1242102/bff3d408-a27a-4b09-b851-d97d0d1912ee)

Happy to help however I can, let me know what info is needed to adjust this.

**Comment by plipof** [comment]
Same issue with me too.

**Comment by simbaja** [comment]
should be resolved in the latest dev branch, HA changed the way they do unit of measure conversions which broke this sensor
