### ISSUE TITLE
Version 0.40 seems to have broken washer info

### ISSUE THREAD

**Issue by sweichbr** [simbaja/ha_gehome#25]
When I updated to 0.4.0, I lost everything except time remaining.  When I reverted to 0.3.12 all entities reappeared.

**Comment by simbaja** [comment]
Do any errors appear in the HA log?  There was a bunch of cleanup done on the laundry stuff and some things may have changed names as well.

**Comment by sweichbr** [comment]
I did not check the logs, but the Integration was showing errors on many of the entities

**Comment by simbaja** [comment]
That may be the result of name changes (we changed the ERD codes on which the HA entities names are based so that things are more distinguished between washers and dryers).  Can you try 0.4.0 again and see what errors it shows in the log?  I don't have a washer/dryer so I'm not able to debug directly.  @warrenrees has been helping me with the laundry stuff, but most likely isn't available for the next couple weeks, so any debugging help you can provide would be appreciated.

**Comment by sweichbr** [comment]
Sorry for the delay. I  reinstalled 0.4.0 and went through the entities.  I found the changes and applied them.  Thanks for your help.

**Comment by simbaja** [comment]
Just to confirm, everything looks good in 0.4.0?

**Comment by sweichbr** [comment]
yup.  Though I did find a bug.  Looks like the "delay time remaining" misinterprets the result as minutes instead of hours.  (i.e. it showed 1 minute for a short time then goes to zero when there are 59 minutes remaining.

**Comment by simbaja** [comment]
Cool, I'll look into that and update accordingly.  Thanks for catching!

**Comment by sweichbr** [comment]
Thanks so much for your quick and informative responses!  I find the GE App so unreliable, so this is really a useful integration.

**Comment by simbaja** [comment]
Yeah, it's very frustrating.  I just wish there was a way to get all the features, but I guess we'll get what we can (for example, we can't get notifications, those are going through Apple/Android native messaging).  Once in HA, it works pretty well, though there are still some random things (like Sabbath mode, which has a significant delay before it changes).

**Comment by simbaja** [comment]
Is there any chance you can run the SDK example and set the delay time to a non-zero value (and let me know what the time is supposed to be so I can do the conversion)?  I just want to make sure I'm interpreting the value at the right unit of measure.

**Comment by simbaja** [comment]
The dev branch should fix the delay time (got confirmation from another user on that one).  You can try the dev branch, but I'll probably publish a new release within the next couple days anyway.  Thanks for your help!
