### ISSUE TITLE
Contributing to the project

### ISSUE THREAD

**Issue by Dirk-Manderin** [simbaja/ha_gehome#250]
I just recently purchased a number of GE Cafe appliances, so if I can provide any information to help with your development, let me know.

**Comment by simbaja** [comment]
Welcome any help for any unsupported devices.  If you go to the SDK (https://github.com/simbaja/gehome), there's an app that'll produce a debug file that can identify new codes from your devices.

**Comment by 1920x1200** [comment]
@simbaja I also would like to contribute. (my oven is missing some modes) I've taken a look at the link you provided but it doesn't state anything about the "app that'll produce a debug file". Please consider adding a section to the documentation with the minimum steps required for people who would like to obtain and share this data.

**Comment by leandroalves-sc** [comment]
I also would like to contribue

**Comment by simbaja** [comment]
Hmm, I think the readme is pretty clear, you need to install the package then under usage, it tells you how to run the application, including all parameters needed.  If you feel it is unclear in some way, would welcome a PR with potential clarifications.
