### ISSUE TITLE
Deauthenticates every few hours and duplicate IDs

### ISSUE THREAD

**Issue by brylee123** [simbaja/ha_gehome#256]
![image](https://github.com/simbaja/ha_gehome/assets/22011502/8d0f6907-5a27-4236-8d98-f7f63b635dc5)

I have tried removing the device (coffee maker), removing the repo from HACS, rebooted, made sure the repo wasn't in custom_components, reinstalled and both issues still persist.

The main issue is that I am required to login every hour or so. The duplicate IDs doesn't seem to have an impact on how it functions since this has been an issue for quite a long time (a few months).

**Comment by simbaja** [comment]
Are there any other errors in the log?  Can update the logger to produce debug logs (see https://www.home-assistant.io/integrations/logger/)?  Additionally any problems when using the SDK directly?

**Comment by brylee123** [comment]
Logger: custom_components.ge_home.update_coordinator
Source: custom_components/ge_home/update_coordinator.py:263
integration: GE Home ([documentation](https://github.com/simbaja/ha_gehome))
First occurred: June 17, 2024 at 11:01:21 AM (1184 occurrences)
Last logged: 4:24:12 PM

could not reconnect: Problem with request, code: 403, will retry in 7.5 seconds
could not reconnect: Could not get OAuth token, will retry in 7.5 seconds
could not reconnect: Problem with request, code: 403, will retry in 15 seconds
could not reconnect: Could not get OAuth token, will retry in 15 seconds
could not reconnect: Problem with request, code: 403, will retry in 30 seconds

====================================================

Logger: homeassistant
Source: custom_components/ge_home/devices/base.py:61
integration: GE Home ([documentation](https://github.com/simbaja/ha_gehome))
First occurred: 1:43:17 AM (4630 occurrences)
Last logged: 4:22:51 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 291, in on_device_update
    self._update_entity_state(api.entities)
  File "/config/custom_components/ge_home/update_coordinator.py", line 308, in _update_entity_state
    _LOGGER.debug(f"Entity {entity} ({entity.unique_id}, {entity.entity_id}) not yet added, skipping update...")
                                      ^^^^^^^^^^^^^^^^
  File "/config/custom_components/ge_home/entities/common/ge_erd_entity.py", line 60, in unique_id
    return f"{DOMAIN}_{self.serial_or_mac}_{self.erd_string.lower()}"
                       ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ge_home/entities/common/ge_entity.py", line 45, in serial_or_mac
    return self.api.serial_or_mac
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ge_home/devices/base.py", line 76, in serial_or_mac
    if (self.serial_number and not
       ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ge_home/devices/base.py", line 61, in serial_number
    return self.appliance.get_erd_value(ErdCode.SERIAL_NUMBER)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gehomesdk/ge_appliance.py", line 136, in get_erd_value
    return self._property_cache[erd_code]
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: <ErdCode.SERIAL_NUMBER: '0x0002'>

Here is some additional information. Hopefully this helps
