### ISSUE TITLE
Can no longer log in

### ISSUE THREAD

**Issue by brianm71** [simbaja/ha_gehome#260]
My Hassio server was down for a while but I have it back up and I can no longer log into the GE SmartHQ component.  Just keeps saying "authentication failed".  I double checked my GE password and even changed it.

**Comment by brianm71** [comment]
That did it, thank you!

**Comment by brianm71** [comment]
As mentioned above, I launched the app, logged out, logged back in and accepted the EULA.  Once done I was able to configure the Hassio integration.

**Comment by tlunsfordCXP** [comment]
To be extra clear:

1. Log out of the app (not the web site)
2. Log back into the app
3. Accept the EULA.

After that, this integration can be reconnected.
