### ISSUE TITLE
Is Canada supported? 

### ISSUE THREAD

**Issue by blackmamba08** [simbaja/ha_gehome#261]
SmartHQ with GE profile loaded in the app. Works fine. 

Integration loaded via HACs custom repository and integration. 

When asked the username and password always error out even though it is the correct password. 

Tried troubleshooting steps bur SmartHQ forces a special character in the password. 

Could the issue be that my region is Canada?

**Comment by karliemeads** [comment]
I am in Canada. I have been successful in adding this integration to Home Assistant for a Cafe Dishwasher.

**Comment by mguaylam** [comment]
Canada is supported.
