### ISSUE TITLE
Integration no longer working

### ISSUE THREAD

**Issue by CPaulisnki** [simbaja/ha_gehome#263]
So I noticed a few weeks ago that I was getting no status updates for any of my devices.  I looked on here and saw a few different problems so I changed my password, agreed to the new TOS, still nothing was working.  I removed the integration and re-downloaded the new integration updating from 0.6.08 to 0.6.1  I've successfully logged back in but now it's not showing any devices at all.  I've restarted HA, I've restarted the server. I've uninstalled and reinstalled the integration multiple times.  I've changed my password again.  Nothing is working.

![image](https://github.com/simbaja/ha_gehome/assets/75965125/e232a299-afa5-44d7-8ef5-afbbdb6b57ca)

**Comment by simbaja** [comment]
Not sure, there seem to be multiple terms you have to accept - you might have to logout of the SmartHQ app as well and log back in there - it presented yet another TOS screen when I did.

**Comment by iamkirkbater** [comment]
Logging out of the app and then back in and accepting the new terms worked to solve this for me. Thanks for the tip!
