### ISSUE TITLE
GE Cafe Refrigerator CGE29DP2TS1 & Refrigerator Convertiable Drawer Mode

### ISSUE THREAD

**Issue by marshalltech81** [simbaja/ha_gehome#265]
Thank you for this integration.  I understand that you cannot test against all devices and I am more than happy to assist in this issue.  

For my GE Cafe Refrigerator CGE29DP2TS1, the "Refrigerator Convertable Drawer Mode" is populating with a drop-down of all "N/A".  I am going to make an assumption and assume that the modes that should be populated are based on page 9 of the following manual.

Please let me know what I can do to be of assistance.  

<img width="347" alt="Screenshot 2024-06-07 at 9 47 23 PM" src="https://github.com/simbaja/ha_gehome/assets/68938002/86bfaefa-039b-4858-b491-5236db59fd9a">

**Comment by marshalltech81** [comment]
Sorry the misspelling is mine :)

**Comment by simbaja** [comment]
Duplicate of #243, should be resolved in the latest Dev branch (will create a release shortly), but feel free to reopen if not resolved.
