### ISSUE TITLE
Could not find appliance in known device list.

### ISSUE THREAD

**Issue by danielgoepp** [simbaja/ha_gehome#269]
I have been getting the warning for quite some time. I reported it as part of #233 but I think that issue was different and resolved all the other messages. I can't tell if this is because of a configuration issue on my side or something with the code. I tried to look at what was happening in the code, but I couldn't figure where these data was coming from without a lot more effort learning. Can you let me know what is causing this, and perhaps what I can do to resolve it?

Home Assistant: 2024.6.4
ha_gehome: v0.6.11
Device: Windows AC
<img width="323" alt="image" src="https://github.com/simbaja/ha_gehome/assets/6578265/04cde7e9-bf10-4a30-8459-9c0cc08600f2">

```
2024-06-24 04:38:57.899 WARNING (MainThread) [custom_components.ge_home.update_coordinator] Could not find appliance D828C949D0E0 in known device list.
```

**Comment by danielgoepp** [comment]
Most other issues I was seeing seem to have cleared up, however I do still see this as of v0.6.12 running on 2024.9.3 - 9/26.

```
2024-09-26 04:44:01.830 WARNING (MainThread) [custom_components.ge_home.update_coordinator] Could not find appliance D828C949D0E0 in known device list.
```

I see this on every restart.

**Comment by simbaja** [comment]
Shouldn't be a concern and has been downgraded to "info" level.  If it annoys you, please configure the logger to exclude it, see [here](https://www.home-assistant.io/integrations/logger).
