### ISSUE TITLE
time_remaining 

### ISSUE THREAD

**Issue by itm1960** [simbaja/ha_gehome#275]
I’ve just installed this integration, and can see sensors for my 2-drawer Fisher & Paykel dishwasher.
For some reason the “time_remaining” attribute for both the upper and lower drawers is set to 4:03, despite the fact that the machine has been idle for a few hours (the last cycle completed about 10 hours ago). A restart of HA made no difference.
I then ran a wash cycle, and the time remaining counted down from 4:00 as expected, but when the cycle ended the time remaining reset itself to 4:03.
I then power cycled the dishwasher, and once again the time remaining for both drawers was reset to 4:03

**Comment by simbaja** [comment]
Might be something with the API, the integration is generally just pulling information from the smarthq servers.  Not sure if it can really be changed, but perhaps if you explore the raw values in the [sdk](https://github.com/simbaja/gehome) debugging, you might find something.  Closing for now, but feel free to open an issue on the sdk repo if you see something promising.
