### ISSUE TITLE
Remote turn off for Laundry

### ISSUE THREAD

**Issue by truffshuff** [simbaja/ha_gehome#277]
Is there a way to include a switch or something to turn the washer and dryer off remotely? The SmartHQ app seems to have this functionality.

**Comment by simbaja** [comment]
If you can identify the command used to do this, it can be incorporated.  You might be able to use the SDK to see what values change as you press buttons/use the official app.

**Comment by simbaja** [comment]
Closing here, but please feel free to go to the [sdk](https://github.com/simbaja/gehome) repo and create an issue there if you have the ability to help figure this out.
