### ISSUE TITLE
Integration stuck at initializing and then error since I restarted my server.

### ISSUE THREAD

**Issue by clowncracker** [simbaja/ha_gehome#279]
Ever since I restarted my server today, I've run into the following issue:

```Logger: homeassistant.config_entries
Source: config_entries.py:586
First occurred: 4:35:06 PM (20 occurrences)
Last logged: 4:35:26 PM

Error setting up entry xxx for climate
Error setting up entry  xxx for light
Error setting up entry  xxx for button
Error setting up entry  xxx for number
Error setting up entry  xxxor humidifier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 231, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_setup_entry
    raise ValueError(
ValueError: Config entry  xxx ( xxx) for ge_home.binary_sensor has already been setup!
```

I followed the steps here: https://github.com/simbaja/ha_gehome/issues/183

I can no longer enter my credentials.  I get a Failed to connect message as soon as I enter them.

![image](https://github.com/user-attachments/assets/52f10afb-23f6-432f-b5a2-42cd6a11d76a)

**Comment by leferm1** [comment]
Chiming in to say that I’m experiencing a similar issue, and my SmartHQ app can’t connect to the server (which is likely causing the HA integration issue) 
![IMG_6923](https://github.com/user-attachments/assets/a1e08c8a-68f1-4147-a485-0ba5871e9e37)

**Comment by smoreland4** [comment]
I found this in logs. Looks like the code needs to be updated. Anyone able to do so??

> Detected that custom integration 'ge_home' calls async_forward_entry_setup for integration, ge_home with title: EMAIL@EMAIL and entry_id: UIDUIDUIDUID, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/ge_home/update_coordinator.py, line 180: self.hass.async_create_task(, please report it to the author of the 'ge_home' custom integration

**Comment by smoreland4** [comment]
Looks like replacing `async_forward_entry_setup` with `async_forward_entry_setups` in the relevant part of the code would resolve it

**Comment by theoneandonlyewok** [comment]
Getting the same issue here, on both HA and the SmartHQ app.

**Comment by admiralroflknife** [comment]
Also having the same issue

**Comment by kyleb822** [comment]
Add me to the list, same issue

**Comment by ChrisP5602** [comment]
I also am experiencing issues since this morning

**Comment by tfberg** [comment]
Since the SmartHQ app is also experiencing the same my guess is that the issue is on the RESTful endpoint side and not with the integration. Just my two cents.

**Comment by clowncracker** [comment]
I'm not having issues with the app, but I am having issues getting it working in Home Assistant.

**Comment by knobunc** [comment]
I just reloaded and it works for me now.  I assume it was an error on their end.
