### ISSUE TITLE
HA 2024.8.1 & ge_home -> won't initialize

### ISSUE THREAD

**Issue by rickeames** [simbaja/ha_gehome#282]
Fresh HA install on unraid via docker.  Created the custom_components folder and copied ge_home to it, relaunched HA and went to add the integration per the instructions.  This is the error I get and I don't see anything in the logs for why this would have happened:

Config flow could not be loaded: {"message":"Invalid handler specified"}

**Comment by dtupper** [comment]
Was able to replicate. Running HA on Debian via Docker.

` Config flow could not be loaded: {"message":"Invalid handler specified"} `

**Comment by staff0rd** [comment]
I'm running on Ubuntu via Docker and saw this though I had used the UI to reboot HA. To solve this, i restarted the docker container, upon which adding the integration no longer threw that error message.

**Comment by dtupper** [comment]
Yep, can confirm a restart fixes it.
