### ISSUE TITLE
Integration Causes HA to crash on update from 2024.7 to 2024.8

### ISSUE THREAD

**Issue by maniscalcojohn** [simbaja/ha_gehome#283]
I was attempting to update my HA from 2024.7 to 2024.8 and could not get it to update. Each time, the HA would crash and roll back to 2024.7. Unfortunately, the logs are sparse on the exact issue, but I did see several comments about this integration in the logs, so I tried disabling it and running the update again, and was successful. 

This comment shows up several times:

WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration ge_home with title: xxxxxxxxxxxxxxxx@gmail.com and entry_id: xxxxxxxxxxxxxxxxxxxxxxxxx, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

The last log before the crash is:

  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError: Home Assistant is stopping

**Comment by danielgoepp** [comment]
Looks like: https://github.com/simbaja/ha_gehome/issues/271

**Comment by danielgoepp** [comment]
@maniscalcojohn are you still experiencing crashes? I can run HA just fine, but am still seeing this warning. #271 was closed, so I opened another issue to track, but then I see yours here too which is still open and looks directly related, the only difference I guess is that I'm not crashing.

**Comment by maniscalcojohn** [comment]
Hi Daniel, Once I downgraded the integration, I was able to update HA. I
just checked it, and it appears to have updated itself without any issues,
so looks like you can close this one out. Thanks!

**Comment by danielgoepp** [comment]
I can't close your issue. I'm just another user like you, I was just experiencing the same thing, and was cleaning up some of my other issues on here, so I figured I would ask you how things were. You can close the issue though, down at the bottom of the page here in the comments.
