### ISSUE TITLE
Washer/Dryer combo unit does not show

### ISSUE THREAD

**Issue by chilton715** [simbaja/ha_gehome#284]
I have a washer/dryer combo unit that doesn't show in the device list. I followed the installation instructions, but nothing shows. I'm not sure what the issue could be.

**Comment by mguaylam** [comment]
Me as well, probably just because the model is not integrated yet.

**Comment by mguaylam** [comment]
Once I started the washer the entities started to appear.

**Comment by simbaja** [comment]
Original issue might be an appliance type that's missing.  Can you go to the [SDK](https://github.com/simbaja/gehome) repo and get some of the logs to help debug?

**Comment by mguaylam** [comment]
@chilton715 can you give this information? I have transitioned to the [GEA adapter](https://github.com/geappliances/home-assistant-adapter) otherwise fell free to close this issue in a week @simbaja if you don't have any news but on my end after a HA restart it was good.

**Comment by simbaja** [comment]
Seems like potentially resolved?  If not, feel free to open a new issue if still present.
