### ISSUE TITLE
GE Refrigerator no longer displays fridge / freezer temperature

### ISSUE THREAD

**Issue by TerribleTesla** [simbaja/ha_gehome#286]
As of a few weeks ago (September 6th), the sensors for fridge / freezer temperature are no longer being reported in Home Assistant.  Otherwise, the rest of the data seems to be reporting correctly. 

(This entity is no longer being provided by the ge_home integration. If the entity is no longer in use, delete it in settings.)

sensor.sv512077_current_temperature_freezer  
sensor.sv512077_current_temperature_fridge   

Are these readings no longer provided by the integration?  

![image](https://github.com/user-attachments/assets/53df28d1-360c-4ecb-9374-02b60f1e149c)

![image](https://github.com/user-attachments/assets/8cca1bf1-9d78-4439-97d1-2ff00819d55d)

**Comment by simbaja** [comment]
From what I can tell, they've removed this from the API responses.  They may have it in the new API in the official app, but I don't have documentation on that.
