### ISSUE TITLE
LS151177 GE Fridge Interior Light

### ISSUE THREAD

**Issue by zoe4196** [simbaja/ha_gehome#293]
All of my sensors on all appliances (fridge, oven, dishwasher, opal icemaker) lose connection from time to time but they come back up after I reload. The most annoying is the interior Backlight of the fridge turns off every time it loses connection. Any ideas on what is causing this? I have to reset it via smartHQ app each time. 

Thank you

**Comment by nickgardnermedia** [comment]
I also have this same issue, thought it might be due to 2024.10.1 but rolled back to 2024.10.0 and it persists.

**Comment by zoe4196** [comment]
I figured it out. I had a script to turn off kitchen lights that just worked by area so it was including the fridge light in the area. Had to change it to individual devices so it only turns off overhead lights.
