### ISSUE TITLE
Refrigerator Interior Light Not Working in `ge_home`

### ISSUE THREAD

**Issue by marshalltech81** [simbaja/ha_gehome#303]
Recently

<img width="585" alt="Screenshot 2024-11-12 at 10 47 13 PM" src="https://github.com/user-attachments/assets/1b9b94b6-6283-433b-8d41-5da1bc18b88d">

A number of elements have become unavailable.  I tried downgrading and that did not work either.

**Comment by outpoints** [comment]
Seems like it was caused by the recent outage a couple days ago. Mine still won’t connect, has yours fixed itself?

**Comment by simbaja** [comment]
Assuming that this has resolved itself, please let me know if it is still occuring.
