### ISSUE TITLE
StringPrep

### ISSUE THREAD

**Issue by yestrdave** [simbaja/ha_gehome#307]
This error originated from a custom integration.

Logger: slixmpp.stringprep
Source: custom_components/ge_home/update_coordinator.py:8
integration: GE Home (documentation)
First occurred: 3:27:15 PM (1 occurrences)
Last logged: 3:27:15 PM

Using slower stringprep, consider compiling the faster cython/libidn one.

**Comment by antisane** [comment]
Been getting this error for ages, does not seem to affect anything.

**Comment by VlastiBroucek** [comment]
and the author/owner doesn't seem to give a damn...

**Comment by simbaja** [comment]
@VlastiBroucek, pretty uncalled for
@yestrdave, if it bothers you, you should be able to exclude from your log using the [logger configuration](https://www.home-assistant.io/integrations/logger)
