### ISSUE TITLE
Error setting up entry GE Home

### ISSUE THREAD

**Issue by derekcentrico** [simbaja/ha_gehome#33]
Good afternoon.  I've tried to setup this using HACS various times today.  Unfortunately, I receive the following error:

> This error originated from a custom integration.
> 
> Logger: homeassistant.config_entries
> Source: custom_components/ge_home/update_coordinator.py:174
> Integration: GE Home (documentation)
> First occurred: 3:51:19 PM (1 occurrences)
> Last logged: 3:51:19 PM
> 
> Error setting up entry GE Home (XXXXXXXXXXXXXXXX) for ge_home
> Traceback (most recent call last):
>   File "/config/custom_components/ge_home/update_coordinator.py", line 172, in async_setup
>     await self.initialization_future
> asyncio.exceptions.CancelledError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/config/custom_components/ge_home/update_coordinator.py", line 172, in async_setup
>     await self.initialization_future
>   File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 45, in __exit__
>     self._do_exit(exc_type)
>   File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 92, in _do_exit
>     raise asyncio.TimeoutError
> asyncio.exceptions.TimeoutError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
>     result = await component.async_setup_entry(hass, self)  # type: ignore
>   File "/config/custom_components/ge_home/__init__.py", line 26, in async_setup_entry
>     if not await coordinator.async_setup():
>   File "/config/custom_components/ge_home/update_coordinator.py", line 174, in async_setup
>     raise HaCannotConnect("Initialization timed out")
> custom_components.ge_home.exceptions.HaCannotConnect: Initialization timed out

Other items from HACS repos are working fine.  

The VM is running Home Assistant OS 6.2, core-2021.8.6, and supervisor-2021.06.8.  

HACS is 1.13.2, 20210620205902

**Comment by simbaja** [comment]
Can you check to see if the latest dev version (0.4.3-dev3) works for you?  See #30 for further discussions

**Comment by derekcentrico** [comment]
Latest dev branch worked.  Closing.
