### ISSUE TITLE
Multiple Air Conditioners appear as a single device

### ISSUE THREAD

**Issue by Xe138** [simbaja/ha_gehome#37]
I have 2 GE Air Conditioners and they appear under a single device with entities for both units.  I would expect these to appear as separate devices containing their respective entities.

![image](https://user-images.githubusercontent.com/50377201/130336288-86589466-aaae-4c35-9655-92ccf7ee4c2a.png)

**Comment by simbaja** [comment]
Thanks for reporting this, can you confirm that 0.5.0-dev1 fixes this?  The issue is that, unlike every other device, A/C units don't appear to present their serial numbers, so I'm using MAC addresses to make the entities.  I missed the same adjustment for the device information - hopefully it's all good now.

**Comment by Xe138** [comment]
With 0.5.0-dev1 the devices are separated, but there is a third device containing no entities that may have been retained from the previous version (GE Air Conditioner).

![image](https://user-images.githubusercontent.com/50377201/130359073-2fa6c130-a0c8-4145-b8cb-a57c273a5482.png)

**Comment by simbaja** [comment]
I think that you'll probably need to either uninstall/reinstall the integration (clearing out any leftovers) or edit your device registry to get rid of that one.  The integration doesn't actually add anything to the registry manually, it relies on HA to manage it (we only add the entities) and HA thinks it still exists.

**Comment by Xe138** [comment]
I'll just disable the device and try not to think about it.

I think the issue is resolved.  Thanks!
