### ISSUE TITLE
AC Temperature sensor in Fahrenheit and not Celsius

### ISSUE THREAD

**Issue by RobertusIT** [simbaja/ha_gehome#40]
Hi,

i open this support, because i make a fresh HA installation, and i see with last ha_gehome-0.5.0-dev3, ( i didn't remember if is already present in previous version ), that there are 2 temperature sensor, in Fahrenheit and not Celsius.

On app, ( Geappliances in europe, SmartHQ in US ) is already setup Celsius.

I remember that was a know issue, when we tested first time the integration.

![image](https://user-images.githubusercontent.com/11599774/131395126-d15c702b-2511-49a8-9919-16cfa16fdbab.png)
sensor.d_ac_ambient_temperature
sensor.d_ac_target_temperature
note. you can see C, but it isn't, because if in my house there was 84 Celsius, i was dead ;)

Should be great if get from app celsius and not Fahrenheit , or when you import any devices, to choose from f to c or viceversa.

Thanks for the amazing support and integration!

**Comment by simbaja** [comment]
Can you give 0.5.0-dev4 a shot and see if it resolves this issue?

**Comment by RobertusIT** [comment]
> Can you give 0.5.0-dev4 a shot and see if it resolves this issue?

Fixed !

Awesome!

And sorry about delay for reply

![image](https://user-images.githubusercontent.com/11599774/132234976-7deed850-0b75-4e4f-8140-93b187165e01.png)
