### ISSUE TITLE
Plan for supporting climate entities

### ISSUE THREAD

**Issue by danielgoepp** [simbaja/ha_gehome#42]
I'm just wondering if you plan on supporting climate entities to allow setting mode and temps for an A/C? I installed the integration and configured it no problem. My A/C shows all the values, but I can't set them because they are all just sensors. I'm just wondering if you have any plans to implement support for climate too? Turning the power on and off as a switch works :)

<img width="491" alt="Screen Shot 2021-09-01 at 4 49 42 PM" src="https://user-images.githubusercontent.com/6578265/131744114-efef855d-6f6c-4ac7-a660-7bd8aa20c5dd.png">

**Comment by simbaja** [comment]
Hmm... it should have the climate control.  Are there any errors in the logs?

**Comment by simbaja** [comment]
Which model do you have?  Looks like a window unit of some sort based on the sensors it's showing.  It should have done the climate entity first, and shouldn't have been able to setup the rest if there's an issue: (see [code](https://github.com/simbaja/ha_gehome/blob/c1e01b79a26b773e53b0824cb67b47f90712a8b6/custom_components/ge_home/devices/wac.py#L21)).  Can you filter the entity list to the ge_home integration?  Maybe it put it somewhere else??

**Comment by danielgoepp** [comment]
My bad, thank you! Sorry to have bugged you:
<img width="497" alt="Screen Shot 2021-09-01 at 5 21 22 PM" src="https://user-images.githubusercontent.com/6578265/131746925-273d5167-75d3-43d5-9dc5-d9801dca728f.png">
