### ISSUE TITLE
GE wall mount split AC unit conversion on Lovelace entity card

### ISSUE THREAD

**Issue by hank-droid** [simbaja/ha_gehome#45]
hi,  first of it all the integration is amazing!
i managed to integrate by GE ac unit. 
when i select the entities card in lovelace however it shows me Farenheit with the C unit
![image](https://user-images.githubusercontent.com/77301662/135750777-da611662-2751-4a2e-84c4-09dc645509f3.png)
or when i select the entity
![image](https://user-images.githubusercontent.com/77301662/135750727-54c9ff85-924e-4880-9b4d-46eec32f7b89.png)
when i pick the Lovelace thermostat card, the units are shown in Celsius which is correct.
![image](https://user-images.githubusercontent.com/77301662/135750821-62517150-4e4f-4556-8b12-f26da1694ab5.png)
![image](https://user-images.githubusercontent.com/77301662/135750865-85dd19da-24d7-4303-8ce6-a7e0d4667057.png)
i checked if anywhere i had settings to select/convert the units, but not success.

**Comment by simbaja** [comment]
Try using the latest pre-release version, I think this is the same as #40 , and should be resolved.  I've been remiss at making a new "production" release, but may try to get it done this week.

**Comment by hank-droid** [comment]
I confirm it is fixed on dev4

thank you!
