### ISSUE TITLE
Microwave Support

### ISSUE THREAD

**Issue by mbcomer** [simbaja/ha_gehome#49]
Is there any intent / desire to add support for microwaves?

Model #: CVM721M2N1S5
Type: Microwave

https://www.cafeappliances.com/appliance/Cafe-2-1-Cu-Ft-Smart-Over-the-Range-Microwave-Oven-in-Platinum-Glass-CVM721M2NS5

**Comment by mbcomer** [comment]
Front panel:

![IMG_0652](https://user-images.githubusercontent.com/6476094/137378152-0f65522a-5c08-42d4-b30d-5e62fdb59ba6.JPG)
![IMG_0651](https://user-images.githubusercontent.com/6476094/137378155-c50275d6-102a-471d-a7d3-dff2f0b965ca.JPG)

**Comment by simbaja** [comment]
OK, so I should be able to at least be able to set a kitchen timer (which I think is the hood timer I've got) and then turn it on to a given power level and for a specified time from the app.  Got it.  Let me see what I can do here.

**Comment by mnestor** [comment]
There is a light and fan on mine, but it looks the same as yours does. I'd be willing to pitch in to get this working here if you can point me in the right direction @simbaja

**Comment by simbaja** [comment]
I think I responded on a different thread on this (@mbcomer had a few requests :)).  @mnestor if you can go to the https://github.com/simbaja/gehome repository and post a debug log, that would be what I need to move this along.   I'll also need some help when it comes time to dealing with the microwave control, but we can tackle that when we get there.  First step is to make sure that we can read all the various properties that the Microwave is exposing, and that's what the debug log will get us.

**Comment by simbaja** [comment]
Also, I just integrated the other functionality into the latest "dev" branch that I could get from @mbcomer's original log.  I still don't have control setup, but at least some things should be working in HA.

**Comment by kksligh** [comment]
Following here - I have a Cafe microwave CEB515P2NSS and I've installed the different Dev branches but it's not showing up in the devices list. Any ideas?

**Comment by mnestor** [comment]
Love it, so sorry I fell off on trying to help out, which I'd much rather have been doing. :(

Now I have a better setup of auto vent+light than that built in chef connect crap. Thank you!!

**Comment by kksligh** [comment]
Following Up - Microwave works great! attached is the sensors that come through:

![image](https://user-images.githubusercontent.com/83232851/178507957-6087ae18-277a-4d13-9fe3-a771e9433a80.png)

**Comment by simbaja** [comment]
Closing as stale, please re-open a new issue if more support is needed.
