### ISSUE TITLE
Sabbath mode icon being deprecated

### ISSUE THREAD

**Issue by mjmeli** [simbaja/ha_gehome#50]
Just a heads up here, I am getting this error as of 2021.10, relating to the Sabbath mode icon.

`Icon mdi:judaism was renamed to mdi:star-david, please change your config, it will be removed in version 2021.12.`

**Comment by schmittx** [comment]
FYI, another one to add to your list:

`Icon mdi:sparkles was renamed to mdi:shimmer, please change your config, it will be removed in version 2021.12.`

**Comment by simbaja** [comment]
I've made the changes in the latest dev version, so I'll close this issue.  These updates will be in the next released version.  I might be a little late (I think 2021.12 is being released today), but hopefully it doesn't cause any issues besides some graphical issues.  You can use the entity customization to fix the issue in the meantime.  Sorry for the delays on this.
