### ISSUE TITLE
Automatic Unit Selection

### ISSUE THREAD

**Issue by vignatyuk** [simbaja/ha_gehome#54]
Currently integration may show incorrect temperature for a fridge like this:

Controls
ZG033204 Freezer
-4 °C
Currently: -3 °C
ZG033204 Fridge
38 °C
Currently: 37 °C

Fridge itself is set to use Celsius degrees. HA is set to use Metric system as well. It's obvious that temperature is in Fahrenheit degrees but it is attributed as it is in Celsius. It should either be converted into Celsius or attributed correctly.

fridge.py should be units aware as it contains this: "units = self.hass.config.units".
By changing units at the Configuration/General/Unit System to the Imperial, integration reports temperature this way:

ZG033204 Freezer
25 °F
Currently: 28 °F
ZG033204 Fridge
100 °F
Currently: 99 °F

As we see in  both cases temperature is wrong. This makes me think that GE always reports temperature in Fahrenheit degrees and reports measurement units separately via API. In this case "ConvertableDrawerModeOptionsConverter(units)" should be used with care in a code as it may do things wrong.

I may provide a help to debug issue if needed.

**Comment by simbaja** [comment]
Interesting, we probably need to have people do more tests in celsius to determine if this is model specific.  Also, this whole conversion is slated to be rewritten to follow the "native value" functionality recently introduced in HA, it can be incorporated during the rewrite.  Might be useful to add a config section to force a unit of measure regardless of what the device says it is.

**Comment by simbaja** [comment]
So, from testing various equipment that I've seen/have, it looks like the appliances always report in Fahrenheit, like you suspected.  In the latest "dev" branch, I've made the adjustment to ignore the device setting.  Can you check to see if things are reported correctly for this version?

**Comment by vignatyuk** [comment]
Hi,

I have tested the dev branch and it appears temperature is now displayed
correctly.

Thanks!

[image: ge.png]
