### ISSUE TITLE
Water lead detect notification on dishwasher GDT535PSROSS

### ISSUE THREAD

**Issue by tslsa229** [simbaja/ha_gehome#56]
Any hopes of getting this data?

**Comment by simbaja** [comment]
Is this data a available in the official app?  Any chance you can send me a debug log of your dishwasher to see if there's anything else in the data we can identify?

**Comment by tslsa229** [comment]
Yep its available status in the app.  I can send you a debug report if you
tell me how to do it.  I looked around the app and didnt see any option.

**Comment by simbaja** [comment]
If you can go to the https://github.com/simbaja/gehomesdk repository, clone it, add the secrets file and run the websocket example, this would generate the log file.  It would be useful if you could figure out how to trigger the sensor so we can see the value change and identify the code faster, but it will hopefully be enough just to have the log.

**Comment by simbaja** [comment]
Closed as stale, please let me know if you're able to collect a little information and I'll try to get it in.
