### ISSUE TITLE
Switches for dishwasher Lock Controls and Sounds

### ISSUE THREAD

**Issue by schmittx** [simbaja/ha_gehome#59]
Is it possible to create switch entities for "Lock Controls" and "Sounds" for dishwasher user settings? Below are logs from toggling within the GE Home app.

Dishwasher = GDF530PGM0CC

Lock Controls Enabled

`Setting ErdCode.DISHWASHER_USER_SETTING to ErdUserSetting(sound=<UserSetting.DISABLE: 0>, lock_control=<UserSetting.ENABLE: 1>, sabbath=<UserSetting.DISABLE: 0>, cycle_mode=<UserCycleSetting.THIRTY_MIN: 4>, presoak=<UserSetting.ENABLE: 1>, bottle_jet=<UserSetting.DISABLE: 0>, wash_temp=<UserWashTempSetting.BOOST_AND_SANITIZE: 3>, dry_option=<UserDryOptionSetting.MAX_DRY: 2>, wash_zone=<UserWashZoneSetting.BOTH: 0>, delay_hours=4, raw_value='043B24')`

Lock Controls Disabled

`Setting ErdCode.DISHWASHER_USER_SETTING to ErdUserSetting(sound=<UserSetting.DISABLE: 0>, lock_control=<UserSetting.DISABLE: 0>, sabbath=<UserSetting.DISABLE: 0>, cycle_mode=<UserCycleSetting.THIRTY_MIN: 4>, presoak=<UserSetting.ENABLE: 1>, bottle_jet=<UserSetting.DISABLE: 0>, wash_temp=<UserWashTempSetting.BOOST_AND_SANITIZE: 3>, dry_option=<UserDryOptionSetting.MAX_DRY: 2>, wash_zone=<UserWashZoneSetting.BOTH: 0>, delay_hours=4, raw_value='043924')`

Sounds Enabled

`Setting ErdCode.DISHWASHER_USER_SETTING to ErdUserSetting(sound=<UserSetting.ENABLE: 1>, lock_control=<UserSetting.DISABLE: 0>, sabbath=<UserSetting.DISABLE: 0>, cycle_mode=<UserCycleSetting.THIRTY_MIN: 4>, presoak=<UserSetting.ENABLE: 1>, bottle_jet=<UserSetting.DISABLE: 0>, wash_temp=<UserWashTempSetting.BOOST_AND_SANITIZE: 3>, dry_option=<UserDryOptionSetting.MAX_DRY: 2>, wash_zone=<UserWashZoneSetting.BOTH: 0>, delay_hours=4, raw_value='843924')`

Sounds Disabled

`Setting ErdCode.DISHWASHER_USER_SETTING to ErdUserSetting(sound=<UserSetting.DISABLE: 0>, lock_control=<UserSetting.DISABLE: 0>, sabbath=<UserSetting.DISABLE: 0>, cycle_mode=<UserCycleSetting.THIRTY_MIN: 4>, presoak=<UserSetting.ENABLE: 1>, bottle_jet=<UserSetting.DISABLE: 0>, wash_temp=<UserWashTempSetting.BOOST_AND_SANITIZE: 3>, dry_option=<UserDryOptionSetting.MAX_DRY: 2>, wash_zone=<UserWashZoneSetting.BOTH: 0>, delay_hours=4, raw_value='043924')`

**Comment by simbaja** [comment]
If the app allows it, I should be able to do it when it comes to changing something on the device.  Right now, all the user settings are read-only in the SDK library (wasn't sure if they were settable when I wrote it); however, I can probably make them read/write without too much issue.  After that, I can then add switch entities into the HA integration.  Work is crazy busy right now, so I haven't had much time to get through this, but I'll add it to the roadmap.

**Comment by schmittx** [comment]
Yeah, the app definitely allows control of both (that's how I generated the logs above).

Good to know about the SDK library being read-only. I looked at it briefly, but wanted to ask the question first before I took a deeper dive.

**Comment by simbaja** [comment]
Thanks to @NickWaterton the SDK is now read/write.  Feel free to take a deeper dive into it if you'd like the controls added.  I might give it a shot at some point, but I've been absolutely swamped lately.  I'll close this for now, but if you're still interested let me know and we'll see what we can do in some later versions.
