### ISSUE TITLE
Error loading configuration flow

### ISSUE THREAD

**Issue by alan21627** [simbaja/ha_gehome#60]
I am running HA core on TrueNAS. When I try to load the integration, I keep getting the following error:

Logger: homeassistant.config_entries
Source: config_entries.py:711
First occurred: 9:43:29 PM (1 occurrences)
Last logged: 9:43:29 PM

Error occurred loading configuration flow for integration ge_home: No module named 'lxml'

Any advice on manually adding the lxml module?

**Comment by simbaja** [comment]
In general it should be just a `pip install lxml` command.  But, if that doesn't work, something on this site might help: https://lxml.de/installation.html

**Comment by softtechs1** [comment]
alan21627, did you find a solution installing lxml on TrueNAS? Having the same issue finding an lxml package.

**Comment by alan21627** [comment]
I ended up reinstalling HA OS as a VM instead of a TrueNAS plugin, then the issue went away.

**Comment by softtechs1** [comment]
I got lxml now installed for python 3.8, however there is an open issue with python 3.9 on Truenas. Thanks
