### ISSUE TITLE
FR: Oven Set Temperature

### ISSUE THREAD

**Issue by MRobi1** [simbaja/ha_gehome#64]
Is it possible to have a sensor created with the temperature the oven is set to? This information is visible within the app, so I hope it's exposed to the api.

IE: When the oven is turned on, it defaults to being set to 350F. Can a sensor be generated to read that data?

I've tried making a template sensor that calculates the raw_temperature and user_temp_offset, but the user_temp_offset doesn't seem to update very quickly so the template sensor usually just ends up displaying the raw_temperature value.

**Comment by simbaja** [comment]
Sorry, got Covid so I've been offline for a while.  I think that this can be accomplished by looking at the attributes of the oven entity, it publishes the `target_temperature` as an attribute that you should be able to read in a template sensor.  Does that give you what you need?

**Comment by MRobi1** [comment]
First and foremost, I hope you're doing well!

This is what I see for attributes while the oven is on:
```
min_temp: 76.7
max_temp: 287.8
operation_list: Off, Bake
current_temperature: 19.4
temperature: 190.6
target_temp_high: null
target_temp_low: null
operation_mode: Bake
display_state: Preheat
probe_present: false
display_temperature: 100
raw_temperature: 67
icon: mdi:stove
friendly_name: Oven
supported_features: 3
```
I do see a target_temp_high and target_temp_low but they both report null. But the temperature attribute does seem to be reporting the target temp so I can use this and make a template sensor to get what I need. 

Basically I'm playing with different ideas on how to best control the oven through HA. The water_heater platform adjusts temps 1 degree at a time which means 50 button presses to bring it from 350 to 400. I'd give up and just go set it at the oven itself lol. I may do a virtual climate device or something like a simple input_select with the most common set temps.

Thanks for pointing me in the right direction!

**Comment by simbaja** [comment]
Ah, you may want to look at https://github.com/nervetattoo/simple-thermostat.  It can be used with water_heater entities and you can set the step size to something more reasonable for an oven.  It's what I'm using in my HA dashboards.
