### ISSUE TITLE
Temperature Units Backwards

### ISSUE THREAD

**Issue by Jamby88** [simbaja/ha_gehome#66]
My fridge is set as Celsius and the values coming in to HA show Fahrenheit values with degrees C as the unit.

Likewise, my oven is set as Fahrenheit and the values come into HA show Celsius values. If I switch the units to Celsius on the oven, the values in HA change to Fahrenheit, but leave the units as degrees Celsius.

**Comment by simbaja** [comment]
Can you try the latest pre-release or "dev" branch?  This should be fixed there, the appliances through the API appear to always transmit Fahrenheit regardless of what the device is set to.

**Comment by palfrey** [comment]
I'm seeing this with latest release on my oven. It's set entirely to Celsius, but HA is showing it as Fahrenheit but with a C after. e.g. I see 356 C (which is the F value), not 180 C.
