### ISSUE TITLE
Looking for Washer Cycle end time

### ISSUE THREAD

**Issue by sweichbr** [simbaja/ha_gehome#67]
So, for the GE washer, there is a laundry_time_remaining sensor and a delay_time_remaining sensor.  I am trying to figure out how I can combine these two and add it to the current time to get an expected end time.

(it should be noted that delay goes from a value to "off" when the delay is disabled or complete).

This is especially useful because the washer only has 2 digits, so the resolution is pretty useless above 99 minutes.

I can't seem to parse the time given in the sensors.

**Comment by simbaja** [comment]
I think that you can use template sensors to add the two times.  You'll need to use an if statement to handle the delay disabled/complete state, but shouldn't be too bad.  I think that https://community.home-assistant.io/t/the-epic-time-conversion-and-manipulation-thread/85786/4 might help.
