### ISSUE TITLE
Integration into Home Assistant Core

### ISSUE THREAD

**Issue by kevchu3** [simbaja/ha_gehome#69]
This project has had a fair amount of development in the past number of months, and I've opened PRs to Home Assistant to see if we can get this put in as a core integration.  For the sake of open source, I've linked them here.  Feel free to contribute!

- HA core PR: https://github.com/home-assistant/core/pull/66220
- HA website PR: https://github.com/home-assistant/home-assistant.io/pull/21572
- HA branding PR: https://github.com/home-assistant/brands/pull/3152

**Comment by donavanbecker** [comment]
Thoughts on Making this a Core Integration now? Seems to work really well.
