### ISSUE TITLE
Temperature can be set on Hot Water dispenser, but there's no way to activate it or set temperature

### ISSUE THREAD

**Issue by joelmoses** [simbaja/ha_gehome#7]
I presume that the water_heater entity should respond to an "on" event - or perhaps expose a "Start" in operation_mode, but it copies "Normal" and "Sabbath Mode" from the Fridge configuration instead. Also, when you use "water_heater.set_temperature" on the hot water dispenser entity, it sets MOMENTARILY but then goes back to zero (looks like on the next poll).

**Comment by joelmoses** [comment]
Researching this, it looks to be the entity needing to add an async on off: https://github.com/home-assistant/core/pull/46599

**Comment by simbaja** [comment]
Any updates to this?  Looks like the updates to support this might be cancelled?  Perhaps we can add a service that will allow us to turn it on/off if not available on the entity?
