### ISSUE TITLE
Simple On/Off Switch

### ISSUE THREAD

**Issue by dshafik** [simbaja/ha_gehome#71]
I'm new to Home Assistant, but installed it _specifically_ to try and get my GE oven into HomeKit using the HA/HomeKit integration. After a few small hiccups I now see my oven in HomeKit which is **amazing**.

_However_, as noted in #53 there are some minor inconveniences, specifically the following:

- You cannot tell if the oven is actually off, as it always says "Heating to 170°F" (no idea why it's 170°F, it's the lowest measurement on the scale though). Home Assistant does show the Cook Mode as "Off".
- While it seems you can set the temperature by moving the slider,  once done, you **cannot then turn off the oven**

I was thinking that maybe you could expose the current value of "Cook Mode" as a simple switch (like Shabbot Mode), that if the Oven is off (Cook Mode = Off), would set the switch to Off, and if it's on any other Cook mode, set it to On. If it's toggled off, then set the Cook Mode to Off.

Maybe it's possible to do this myself in HA with the data available and some scripting?

**Comment by dshafik** [comment]
This can be accomplished by using a series of automations and input_booleans. Just be careful where you put the switch in your home otherwise "Hey Siri, turn on/off the Kitchen" will turn on/off the oven 😱

**Comment by carinconc** [comment]
Can you help me figure out how to use input_booleans and automations to turn on and off the oven? Thank you in advance for your help.
