### ISSUE TITLE
Error on setup

### ISSUE THREAD

**Issue by georgiosdelimpasis** [simbaja/ha_gehome#80]
Setup of platform ge_home is taking longer than 60 seconds. Startup will proceed without waiting any longer.

**Comment by LordNex** [comment]
I had this once and in the logs it was due to invalid credentials. Try checking your logs and see if you find anything similar.

**Comment by simbaja** [comment]
I saw from a prior comment that it does indeed seem to be related to credentials.  I'd try switching between US/EU and also making sure the integration is fully updated.

**Comment by modestopuente** [comment]
Same problem with my devices. After update the integration some days ago I can not access my devices. EU zone, tested with the latest dev and Master versions and Credentials are ok.

**Comment by simbaja** [comment]
Did you try US zone to see if it worked?  If so, I'd suggest running the example from [simbaja/gehome](https://github.com/simbaja/gehome) and generating a debug log, it might illuminate your issue.

**Comment by LordNex** [comment]
Best way I've found to get it at least functional in Home Assistant is to add it separately to HA as a HomeKit Controller. Usually after you add it to the normal HomeKit but it's not mandatory. I still can't get GEs shitty app to work, did great for the first 3-6 months after purchase while they were still new. But it seems like GE could care less

**Comment by LordNex** [comment]
Great
