### ISSUE TITLE
Integration no longer starting up

### ISSUE THREAD

**Issue by dcj** [simbaja/ha_gehome#82]
I installed this integration about 5 months ago, and it has been working fine.
Yesterday, it began failing to start.
I see messages in my logs like:
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:297
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 11:03:10 AM (1 occurrences)
Last logged: 11:03:10 AM
Setup of platform ge_home is taking longer than 60 seconds. Startup will proceed without waiting any longer.
```
and
```
Logger: homeassistant.config_entries
Source: custom_components/ge_home/update_coordinator.py:164
Integration: GE Home ([documentation](https://github.com/simbaja/ha_gehome))
First occurred: 11:02:49 AM (1 occurrences)
Last logged: 11:02:49 AM
Error setting up entry Ovens for ge_home

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gehomesdk/clients/async_login_flows.py", line 76, in async_get_authorization_code
    code = await async_handle_ok_response(session, await resp.text())
  File "/usr/local/lib/python3.9/site-packages/gehomesdk/clients/async_login_flows.py", line 111, in async_handle_ok_response
    raise GeAuthFailedError(f"Authentication failed, reason: {reason}")
gehomesdk.exception.ge_auth_failed_error.GeAuthFailedError: Authentication failed, reason: Invalid credentials

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 162, in async_setup
    await self.async_start_client()
  File "/config/custom_components/ge_home/update_coordinator.py", line 183, in async_start_client
    await self.async_begin_session()
  File "/config/custom_components/ge_home/update_coordinator.py", line 193, in async_begin_session
    await self.client.async_get_credentials(session)
  File "/usr/local/lib/python3.9/site-packages/gehomesdk/clients/base_client.py", line 188, in async_get_credentials
    await self.async_do_full_login_flow()
  File "/usr/local/lib/python3.9/site-packages/gehomesdk/clients/base_client.py", line 192, in async_do_full_login_flow
    self.credentials = await self._async_do_full_login_flow()
  File "/usr/local/lib/python3.9/site-packages/gehomesdk/clients/websocket_client.py", line 63, in _async_do_full_login_flow
    await self._async_get_oauth2_token()
  File "/usr/local/lib/python3.9/site-packages/gehomesdk/clients/base_client.py", line 215, in _async_get_oauth2_token
    oauth_token = await async_get_oauth2_token(
  File "/usr/local/lib/python3.9/site-packages/gehomesdk/clients/async_login_flows.py", line 147, in async_get_oauth2_token
    code = await async_get_authorization_code(session, account_username, account_password, account_region)
  File "/usr/local/lib/python3.9/site-packages/gehomesdk/clients/async_login_flows.py", line 83, in async_get_authorization_code
    raise GeAuthFailedError(f'Could not obtain authorization code') from exc
gehomesdk.exception.ge_auth_failed_error.GeAuthFailedError: Could not obtain authorization code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ge_home/__init__.py", line 45, in async_setup_entry
    if not await coordinator.async_setup():
  File "/config/custom_components/ge_home/update_coordinator.py", line 164, in async_setup
    raise HaAuthError("Authentication failure")
custom_components.ge_home.exceptions.HaAuthError: Authentication failure
```
AFAIK, my auth credentials to the GE portal/app have not changed (the iOS app I use continues to see my 2 ovens, and works fine)

Other stuff I did yesterday:

- Updated to core-2022.6.6
- Installed a bunch of bleeding edge addons and integrations for the "Matter" workshop, to see the details of what I installed: https://docs.google.com/document/d/1MldgA337wHTEx-vPkoxlCqKHrhVm5QIcHV32iLsv_2k/edit
```

I don't know for certain that there is an issue with the GE integration, but everything else I have installed/configured continues to work fine...

**Comment by simbaja** [comment]
A few things you can try: 1) update to the latest version 2) uninstall/reinstall the component, 3) download docker desktop and run HASS in that environment, and test to see if it works there.

**Comment by LordNex** [comment]
It tells you right in the log that you have invalid credentials. Did you possibly change your password? Try removing it and read ding the integration with updated credentials.

**Comment by NickG365** [comment]
I ran into a similar (if not the same) issue.  The password that I had previously set for my account no longer worked, even though I was still logged into the mobile app (albeit from years ago).  It seems GE has changed things a bit since I originally created the account.  Of course, their password reset system wasn't working, either.  It would send me a link to a slightly different page to request a new password reset link, and then just kept me in that loop, never sending me a link that would actually let me change it.

What seemed really odd was that this was all through a Salesforce app--I suppose they moved their authentication and account management over there.  Eventually, I found a ["passwordless login" page](https://appliances.force.com/Cafe/s/passwordless-login?language=en_US&startURL=%2Fapex%2FCustomerSSO), which will email you a one-time code to log in with instead of your (now invalidated) password.  After logging in with that code, it required I set a new password, and of course, the complexity requirements had changed such that my old password hadn't met them.  I assume this is why it would no longer let me in.  Hope this helps!

**Comment by dcj** [comment]
Thanks for the responses above.
When I first created my account with the `SmartHQ` app, I used my iPad.
After the auth advice above, I attempted to connect with my iPhone, and it complained about my credentials.
I did the "reset my password" dance, and set my NEW password to what I strongly believe was my old/previous/existing password (Because I keep it in a password manager, and used copy/paste)
Then I was able to log in via the iPhone app, and my iPad app continues to work.
I restarted Home Assistant to no avail.
Later, I deleted the integration from the HA, restarted, and added it back
In the configuration that popped up, I added my user/password (which is almost certainly the same as before)
The integration succeeded this time....

Some comments/questions:

- It would be nice if I could re-enter my user/password to this integration without deleting/reinstalling.....
- Is it **technically possible** to reverse engineer the API to the appliances, so this (or a similar) integration didn't have to work through the cloud?  Not saying that would be easy, or asking/expecting anyone to jump in and start working on that!  For example, the author of the Lennox S30 integration jumped through all kinds of MITM proxy hoops to figure out a way to reverse engineer that API, and after a ton of work, he has it working very well.  Just wondering if there is any reason a similar effort wouldn't be possible?
- 
- 
-

**Comment by simbaja** [comment]
No reason that the API couldn't be reverse engineered.  In fact, there are a few people out there that are connecting devices to the diagnostics port which enables serial communication/control.  It probably wouldn't be too much of a stretch to get something local working using that technique.  It would probably be more involved to intercept the device <-> server communications, but probably possible.  I know I'd like to have local control, but I haven't had the time to investigate the feasibility.
