### ISSUE TITLE
Cannot Get Window Unit In App

### ISSUE THREAD

**Issue by LordNex** [simbaja/ha_gehome#84]
I'm not sure if you can help with this or not but I've been trying to get my window unit to install in the GE or SmartHQ apps and neither will install. It adds it to the network but then says that it cannot find the device in the cloud and to try and relaunch the app. I have it in  Home and it's functional but with minimal settings. Do you know of a way to get it to pull install it into the app or possibly another way of installing it into home assistant? I was thinking it was a blocked port but I set it in my DMZ just to make sure and it still fails. Thanks for any help and for putting out good code! No issues installing it into HACS and getting it integrated. Just don't have anything in the app for it to integrate.

**Comment by simbaja** [comment]
Only thing I ran into was that it didn't really like having a 5g and 2.4g network named the same thing, so I isolated all my devices onto a 2.4g network and it's been pretty stable.  I don't really have another way to get it integrated, we're leveraging their device management infrastructure unfortunately.

**Comment by LordNex** [comment]
Isn't complete so shouldn't be closed

**Comment by simbaja** [comment]
This is outside the scope of this integration.  Once you can get your appliances added to the official app, it should work with the integration.  If the integration doesn't work after adding to the official app, please open a new issue.
