### ISSUE TITLE
ISSUE - Cafe Microwave CEB515P3MDS showing up in HA twice and switching back/forth from active/inactive

### ISSUE THREAD

**Issue by kksligh** [simbaja/ha_gehome#89]
I have a strange bug to report for the Cafe Microwave CEB515P3MDS.  Currently, this microwave shows up as 2 separate devices in HA.  See the image attached.  The odd thing is, one of those devices will be active/working and the other with be unavailable - and this alternates randomly.  Meaning, the one that will be working with become unavailable and the one that wasnt working, will suddenly be working.  There seems to be no reason for why they switch, other than I'm guessing it disconnects from the wifi for whatever reason and then reconnects which apparently triggers this switching device.

![image](https://user-images.githubusercontent.com/83232851/178509133-03209de4-9313-4141-b39c-3ffd76371948.png)

currently active device....
![image](https://user-images.githubusercontent.com/83232851/178510375-e36b3980-b44c-4677-b5ca-3ca294e475fd.png)

currently inactive device...
![image](https://user-images.githubusercontent.com/83232851/178510532-50fbed87-4be9-4a47-98fa-743699467de4.png)

as noted, these will randomly switch from active to inactive.  Never both active at the same time.

**Comment by kksligh** [comment]
attached is the full log from this morning on Debug
[GE Logs.txt](https://github.com/simbaja/ha_gehome/files/9094036/GE.Logs.txt)
.

**Comment by simbaja** [comment]
Not sure why, but it seems like it's return a zero value for your serial number - internally, the integration uses the serial or mac address as the unique identifier, so it's getting confused when that changes unexpectedly.  Since a zero value is invalid, I've updated some of the detection logic for that, which should resolve it.  I'll get that into the next pre-release version and once verified as fixed make it generally available.

**Comment by kksligh** [comment]
Awesome, thank you!!

Thanks,

Kale Sligh
________________________________

**Comment by kksligh** [comment]
> Not sure why, but it seems like it's return a zero value for your serial number - internally, the integration uses the serial or mac address as the unique identifier, so it's getting confused when that changes unexpectedly. Since a zero value is invalid, I've updated some of the detection logic for that, which should resolve it. I'll get that into the next pre-release version and once verified as fixed make it generally available.

unfortunately, this fix is causing my entire system to go unavailable.  Whats frustrating is its completely random.  I dont see errors in the logs, it just causes all my devices to go unavailable.  My suspicion is the block you put on the all zeros serial number is causing it.  This seems to be isolated to just my situation bc of the microwave not showing a number and then showing a number - but I would rather the builds work at this point than it not allowing me to update to the latest builds.  

I am still trying to capture the logs - if any - but I can show you with the image below, my system keeps going in and out of availability for devices that have nothing to do with this fix.  When I roll back to a build that doesnt have this fix, its stable and works fine.

![image](https://user-images.githubusercontent.com/83232851/182617338-10ef087c-20f7-4ae5-9f0f-b18c11f28e17.png)

**Comment by simbaja** [comment]
Can you remove your microwave from SmartHQ?  The fix existed in older versions too - it was just expanded slightly to account for a varying number of zeros.

**Comment by simbaja** [comment]
Also, you may want to try setting your logging to debug, it might catch something happening.

**Comment by kksligh** [comment]
My logs are on debug

I can remove it but it works with previous builds.  I have to deal with the random change of device, but I'd rather deal with that until I can replace or get GE to do something than it not work at all.  

This seems to be a fix for my specific issue - so it would be awesome if you can remove it.  I am about to get logs for my mini fridge via Python, so I want to keep up with the latest builds and still have my microwave.  If its a lot of work, I'll be glad to compensate for your efforts.  I do appreciate everything youre doing!  Sorry to nag on this issue of mine.

**Comment by kksligh** [comment]
BTW - I'm watching this all day until I see it go unavailable and hopefully I can get the logs of anything that is happening.  Thats the ultimate fix but I have struggled for about a week finding anything.

**Comment by simbaja** [comment]
It's actually not a specific fix for you - it's an expansion of some existing code to handle a "00000" serial number - yours just had more zeros than the original case, so I made it handle a variable number of zeros.  The issue is probably somewhere else where it's now getting confused by the switching back and forth/reconnects/etc, so need to figure out the root issue to resolve it.  Removing the microwave is a debugging step to ensure it really is related to the microwave and not something else that coincidentally appeared at the same time as the code change.

**Comment by kksligh** [comment]
Gotcha - I'll work on it and get back. Thanks for your help and patience!

Thanks,

Kale Sligh
________________________________

**Comment by kksligh** [comment]
And of course - I've been monitoring all day long...been completely stable, no issues 😂😂. I'm sure I just jinxed it.

Thanks,

Kale Sligh
________________________________
