### ISSUE TITLE
Can't configure via UI

### ISSUE THREAD

**Issue by draftydesert277** [simbaja/ha_gehome#90]
Getting the "unable to configure via UI" error with a fresh (manual) install:

![image](https://user-images.githubusercontent.com/83384940/178905501-13003502-d63e-4e45-bcc9-09998e4f13ed.png)

![image](https://user-images.githubusercontent.com/83384940/178905587-955a7817-53cb-432f-b766-64a6197784f2.png)

Thinking maybe it could be related to 2022.7?

ETA my logs:

![image](https://user-images.githubusercontent.com/83384940/178905751-602b47db-f268-4f7e-ae13-2a5e293c9b53.png)

**Comment by simbaja** [comment]
I don't see subdirectories in the first screenshot.  There are a lot more files that should be there, can you check to make sure you've copied files and subdirectories?

**Comment by draftydesert277** [comment]
> I don't see subdirectories in the first screenshot. There are a lot more files that should be there, can you check to make sure you've copied files and subdirectories?

You were absolutely right - I missed the subdirectories and needed to use Samba to copy them over. All working now, and just wanted to say thank you so much for your work on this integration!
