### ISSUE TITLE
Window AC unit showing incorrect temperature

### ISSUE THREAD

**Issue by jwagner0789** [simbaja/ha_gehome#92]
HA is showing the target temperature incorrectly(tens of thousands). I can only resolve this if I go to the Smart HQ app and set the temperature.

**Comment by simbaja** [comment]
Can you provide a debug log from the websocket_example in the simbaja/gehome repository?  That would help me diagnose the values you are seeing.

**Comment by jwagner0789** [comment]
Not sure if this is what your asking for. I just turned on debug for the ge_home component. 
![image](https://user-images.githubusercontent.com/78943457/182444166-6daa8710-7ac3-4a02-adaa-69e29a640cd9.png)

**Comment by simbaja** [comment]
That's helpful.  Does the climate control also show an incorrect set point?  What is the appliance set to?  What model is it?

**Comment by jwagner0789** [comment]
Currently, it is set to 74. Model: AHTK12AAW1
![image](https://user-images.githubusercontent.com/78943457/182446356-335b6ff3-57ac-48d0-8014-75f4ea04376d.png)

**Comment by simbaja** [comment]
What does the SmartHQ app show for this?  If it shows correctly, we might need to get a full debug log by running the underlying code from the simbaja/gehome repository (this runs in Python, not Home Assistant)

**Comment by jwagner0789** [comment]
SmartHQ is accurate. Not sure how to preform the next steps.

**Comment by simbaja** [comment]
If you can't run the python project, you might be able to just turn on debugging overall (instead of for the component) and find the gehomesdk calls.  What I'm looking for is on startup, it should enumerate every value that's available and then we can see what is going on and locate the correct key to fix this.

**Comment by simbaja** [comment]
Ok, I made an easier way to get to the data needed.  Install gehomesdk (`pip install gehomesdk`) then run `gehome-appliance-data`. It'll ask for your credentials, but should display the details I need.

**Comment by ChrisCrewdson** [comment]
I get the same issue occasionally, but have not yet been able to capture it with `gehome-appliance-data`. It only happens rarely for me and only in the "Target temperature" as you can see in the attached image.
![2022-08-13 (2)](https://user-images.githubusercontent.com/597792/184517313-727229ce-0015-4f2a-9da8-79b651752c03.png)

It is interesting that for me, the error values are the same set of values: the first two peaks are 10791 and the other peaks are 10222.

I think this might have something to do with a power loss based on when the spikes have been, but I have not been able to trigger it.

Perhaps a workaround would be to throw out any data above 1000? I can't see a case where that would be a valid value.

**Comment by simbaja** [comment]
@jwagner0789 is it always these higher temperatures, or is it only sometimes like @ChrisCrewdson ?  If it's only sometimes, I think his suggestion could work.

**Comment by jwagner0789** [comment]
Yes, my values are always greater than 15,000. So setting a 10,000 limit should work.

**Comment by simbaja** [comment]
Is it ever correct?  Or always wrong?  If always wrong, I think we might need another approach (which needs data from the application I mentioned)

**Comment by jwagner0789** [comment]
It's occasionally correct. Usually when I call a service and set the temp it will stay correct for a little while. ![Screenshot_20220816-180654~2.png](https://user-images.githubusercontent.com/78943457/184993922-fbfa7ab5-fc08-4914-b69f-6151d90cc8e3.png)

**Comment by simbaja** [comment]
Are you still experiencing this?  Apologies, really hard to figure out when I don't have a way to reproduce myself...

**Comment by ChrisCrewdson** [comment]
I no longer own this AC unit. I think ignoring values above 10k is still a reasonable (although strange) solution.

**Comment by simbaja** [comment]
I don't know if this is still happening, but please feel free to submit a pull request to add the required functionality.
