### ISSUE TITLE
Service Calls to Cafe Hood

### ISSUE THREAD

**Issue by claudermilk** [simbaja/ha_gehome#94]
When a service call in Node-RED is sent to the Cafe Hood for either the hood_fan_speed or hood_light_level entities, the command seems to be getting set to both. When the option is not "High" or "Off" an API error is thrown stating that the setting in not valid for the entity that it does not apply to. For example, setting the hood_fan_speed to "Medium" does that and throws an error that "Medium" is not valid for hood_light_level. When "High" or "Off" is sent, then both entities are set to that even if only one was called.

**Comment by claudermilk** [comment]
I had to reload HA and took another look at this. What I am seeing is in Node-Red the command to turn on the hood_light and/or fan_speed is also sending the on command to the oven light. That is why I am seeing the High and Medium values flagged as invalid.

**Comment by simbaja** [comment]
Did you figure this out?  I don't use Node Red, so it may be something in there.  I'm going to close for now, but if you're still running into problems, I can reopen.

**Comment by claudermilk** [comment]
Sorry, my entire HA system has been dead for months. :( I have a CM4 on its way for the new HA Yellow to try rebuilding. I'll get back to this in a little while.
