### ISSUE TITLE
Cafe Beverage Center 

### ISSUE THREAD

**Issue by ichrispod** [simbaja/ha_gehome#96]
Hi - I was wondering what it would take to extend support for the Cafe Beverage Fridge.  It show's up in my setup now (bar fridge), but the only option is Sabbath Mode.  I would like to see if the following could be included (based on the app):

- Door Status (open/closed)
- Lighting - Intensity (0-100%)
- Lighting - Display Mode (on/off)
- Lockout Mode (on/off)
- Temperature

Happy to provide anything you may need.  As you can see, I have 9 GE Appliances (Espresso maker not shown)

Cafe:
- Refrigerator
- Beverage Center
- Microwave
- Dish Washer
- Espresso Maker

Profile:
- Opal Ice Maker 2.0

Standard:
- Oven
- Washer
- Dryer

<img width="271" alt="image" src="https://user-images.githubusercontent.com/37044780/181828702-c8e6fdc0-429f-4b0a-968b-b28cb983d754.png">

**Comment by kksligh** [comment]
I have the same device. I'm hoping you're a little more advanced than I with coding. Here's what the developer needs to build out the functionality. I have the same request and here's the response.


"This can be done, but you'll need to get the raw debug log from the underlying API package (simbaja/gehome). Basically, you'll need to clone that, and then run the websocket_example for a minute to let it pull all the information that we'll need to get the sensors here. At that point, we can work through interpreting the data, then can add to the integration."

**Comment by simbaja** [comment]
Ok, I made an easier way to get to the data. Install gehomesdk (`pip install gehomesdk`) then run `gehome-appliance-data`. It'll ask for your credentials, but should display the details I need.

**Comment by simbaja** [comment]
@ichrispod, I've added the functionality to the latest dev branch (0.6.5-dev1), give it a shot, but based on @kksligh's feedback, looks like we're good here.

**Comment by ichrispod** [comment]
I deleted the integration and pulled from the 0.6.5-dev1 branch (opens HACS, clicked on your tile, clicked re-download, choose the 0.6.5-dev1 version.  restarted HASS, re added the integration and it's still only showing Sabbath Mode as an available control.

**Comment by simbaja** [comment]
Maybe it's a different model from @kksligh's version?  Can you run that application and post the log?
