### ISSUE TITLE
Authentication lapses

### ISSUE THREAD

**Issue by draftydesert277** [simbaja/ha_gehome#97]
My GE fridge has become unavailable due to an authentication issue every hour pretty consistently for several days now:

Logger: gehomesdk.clients.base_client
Source: /usr/local/lib/python3.10/site-packages/gehomesdk/clients/base_client.py:151
First occurred: July 20, 2022 at 7:46:21 AM (604 occurrences)
Last logged: 10:54:10 PM

Error refreshing authentication: Connection closed

Here's an example of my history:

![image](https://user-images.githubusercontent.com/83384940/182290515-25b6056e-f2bc-4cad-b381-c65e2e8566df.png)

This generally seems to resolve itself after 10-20 min, but in the meantime the device and entities are unavailable. Anything more I could provide to help debug?

**Comment by simbaja** [comment]
That timing coincides with the websocket timeout (GE only allows one-hour connections for websockets, so we have to refresh every hour).  It should be doing that in the background though, so not sure why it's actually showing up unless it's having a problem during refresh.  Can you set debugging for the custom component on and post the log during the time it loses connection?

**Comment by draftydesert277** [comment]
> That timing coincides with the websocket timeout (GE only allows one-hour connections for websockets, so we have to refresh every hour). It should be doing that in the background though, so not sure why it's actually showing up unless it's having a problem during refresh. Can you set debugging for the custom component on and post the log during the time it loses connection?

Absolutely can, I'll get it going when I get home.

**Comment by draftydesert277** [comment]
> That timing coincides with the websocket timeout (GE only allows one-hour connections for websockets, so we have to refresh every hour). It should be doing that in the background though, so not sure why it's actually showing up unless it's having a problem during refresh. Can you set debugging for the custom component on and post the log during the time it loses connection?

Well I thought I could do this, but am lost. How do I enable debugging for the custom component? Appreciate your patience!

**Comment by simbaja** [comment]
should just be adding a little configuration, see: https://www.home-assistant.io/integrations/logger/

**Comment by draftydesert277** [comment]
Thanks for the help simbaja. Funny enough, this has not happened in weeks, so I'm not able to reproduce or provide logs. Guess that means it's "solved"! haha
