### ISSUE TITLE
GE Air Conditioner "Eco Mode" mislabeled as Auto?

### ISSUE THREAD

**Issue by matthewleta** [simbaja/ha_gehome#98]
Heya! first off, thanks for all the work y'all have done on this!

I noticed that for my GE air conditioner (model AEC08LY) has an "eco" mode. In the entity options for ac_operation_mode, it lists "auto" rather than "eco" (and this particular AC doesn't have an auto mode for operation. it has "auto" for fan, but that is already correct). selecting Auto does change it to eco, so this is more of a UI thing than an operational one.

 I'm not sure if this is just a generic solution or not, but I figured I'd at least raise it since I noticed it.
 
 Thanks again!

**Comment by simbaja** [comment]
Yeah, unfortunately, HASS only has a pre-defined set of modes, so "Eco" was mapped to "Auto".  Probably the best that can be done for now, until (and unless) HASS allows customizable modes.
